### ISSUE TITLE
Wrong type for each looped item in `rxFor`  and mismatching type for `rxFor` directive

### ISSUE THREAD

**Issue by exequiel09** [rx-angular/rx-angular#1195]
# Description

`rxFor` returns incorrect type for each looped item. See attached screenshot

`rxFor` type error:
![rxfor-type-error](https://user-images.githubusercontent.com/1289472/152517430-27393d00-5de4-4224-a621-37bb8e35c368.png)

source observable:
![source](https://user-images.githubusercontent.com/1289472/152517092-9ee68c67-7800-485f-b0b3-e3fbc81fa4cd.png)

looped item:
![loop-item](https://user-images.githubusercontent.com/1289472/152517109-7ae040bd-074a-491d-8cc3-5727f05bccb7.png)

Sample build error in stackblitz repro:
![from stackblitz](https://user-images.githubusercontent.com/1289472/152516356-c02d9636-f20f-4f51-9fce-76937339a681.png)

# Steps to Reproduce the Issue

Sample repro in StackBlitz: https://stackblitz.com/edit/angular-egwkfk
Repo created by StackBlitz: https://github.com/exequiel09/rxfor-test

# Environment

Angular CLI: 13.1.1
Node: 16.13.2
OS: macOS 12.2

TypeScript config:
enableIvy: true
strict: true

**Comment by hoebbelsB** [comment]
hey @exequiel09 ty for reporting! We are aware that we have typing issues with rxFor. It somehow derives it's type from the `trackBy`. So if you give it a proper function like `(i: number, item: Data) => data.id` it will derive the proper type in the template. 
We are working on it :+1:

**Comment by exequiel09** [comment]
Hey @hoebbelsB thanks for the quick heads up on the quick fix. lemme try that suggestion of yours.

**Comment by exequiel09** [comment]
hey @hoebbelsB ! it fixed the looped item type but the `rxFor` error type remains.

Screenshot:
<img width="591" alt="Screen Shot 2022-02-04 at 7 21 03 PM" src="https://user-images.githubusercontent.com/1289472/152520819-a04eca88-c07c-4ce5-aa6a-f653fdc82a6f.png">

**Comment by hoebbelsB** [comment]
hey @exequiel09 is this maybe a stackblitz related issue? I can reproduce it in the stackblitz, but with a freshly created `ng new` workspace it defers the type correctly. Even without `trackBy` :thinking: 

Here is a link to a test repo: https://github.com/hoebbelsB/ng-13-rxfor

**Comment by exequiel09** [comment]
Hey @hoebbelsB  On the screenshots above, it's not a stackblitz code but rather an actual Angular v13 app. I'll check your test repo 👀

**Comment by hoebbelsB** [comment]
i've also noticed that your stackblitzes are using angular v12. Maybe that's an issue?

**Comment by exequiel09** [comment]
Getting this on the repo you gave me @hoebbelsB 

![Screen Shot 2022-02-04 at 8 33 14 PM](https://user-images.githubusercontent.com/1289472/152529779-f8f6ee93-54cd-4244-9482-4ca74ed736b0.png)

**Comment by exequiel09** [comment]
> i've also noticed that your stackblitzes are using angular v12. Maybe that's an issue?

I'm not sure but the same happens to me on Angular v13 project.

**Comment by hoebbelsB** [comment]
@exequiel09 you are completely right, my idea just tells me everything is right, didn't even try to build :facepalm: .

We need to take a closer look as it seems...

**Comment by exequiel09** [comment]
There are 2 issues here the rxFor type mismatch and the looped item type which has obviously has a workaround which you suggested @hoebbelsB
