### ISSUE TITLE
@rx-angular/template depends on @angular/platform-browser v12

### ISSUE THREAD

**Issue by jochenjonc** [rx-angular/rx-angular#1261]
# Description

When doing an `npm install` on an Angular 13 project with the @rx-angular/template package, it cannot resolve the @angular/platform-browser@"12.2.16" dependency.

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/platform-browser@"12.2.16" from @rx-angular/template@1.0.0-beta.32
npm ERR! node_modules/@rx-angular/template
npm ERR!   @rx-angular/template@"1.0.0-beta.32" from the root project
```

# Steps to Reproduce the Issue

New Angular 13 project and then install @rx-angular/template

**Comment by zandorstorm** [comment]
npm install --save @rx-angular/template @rx-angular/cdk --force

it worked for me
