### ISSUE TITLE
Question: multiple connect() calls for the same key

### ISSUE THREAD

**Issue by tmtron** [rx-angular/rx-angular#1318]
# Question

What is expected to happen, when we call `connect()` multiple times for the same state-key?

E.g. Let's look at the example code from [Passing observables directly](https://github.com/rx-angular/rx-angular/blob/main/libs/state/docs/snippets/passing-observables-directly.md#passing-observables)

```typescript
  @Input()
  set users(users$) {
    this.connect('users', users$);
  }
```
In this case the input setter directly calls `connect()`.  
I guess when the parent later passes another observable to the input, the intention is to unsubscribe from the previous one.  
As far as I can see that is currently not the case.  

So should the implementation be changed to unsubscribe, or is it the responsibility of the library users, to handle this case (in this case, it would be good to update the docs of the connect method)?

**Comment by hoebbelsB** [comment]
it is the responsibility of the user to take care of this scenario. You won't be able to unsubscribe from it at this components level, though. The example probably doesn't state it clear enough. On the other hand, an observable is already a datastructure emitting values over time, so we are expecting the observable to never change, instead just emitting its values.

It also means you are able to connect different sources to the same key, they can emit at different times, but interact with the same property of your state.

```ts
interval$ = interval(200);
state.connect('time', interval$);

intervalSlow$ = interval(2000);
state.connect('time', intervalSlow$);

// is the same as
state.connect('time', merge(intervalSlow$, interval$));
```

I hope I could answer your question :)
