### ISSUE TITLE
Dropping cdk/zone-less/rxjs package

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#1355]
# Problem Solved By The Feature

Due to the the maintenance effort and complex codebase we decided to remove RxJS code from the lib. This may cause some trouble in other projects that rely on this features.

# Solution

One way of lessening the problems for people relying on this features is to publish it under another repo/lib and have it mentioned in the RxAngular docs.

* [x] deprecate public API for `zone-less/rxjs` https://github.com/rx-angular/rx-angular/pull/1305
* [x] release version with deprecated API
* [x] create new repo `rxjs-zone-less` https://github.com/rx-angular/rxjs-zone-less
* [x] move out `cdk/zone-less/rxjs` into new repo

# alternatives Considered

just delete it without a separate release

**Comment by edbzn** [comment]
Closing as it is done.
