### ISSUE TITLE
[Question]: About ngrx/component-store

### ISSUE THREAD

**Issue by tmtron** [rx-angular/rx-angular#1379]
NgRx version 14 also has:
- a [component-store](https://ngrx.io/guide/component-store)
- a [let-directive](https://ngrx.io/guide/component/let)
- a [push-pipe](https://ngrx.io/guide/component/push)

These look very similar to what the rx-angular project has to offer.

Are there any advantages of one over the other?  
Is this lib still relevant in the future, or should we refactor our code to use NgRx?

**Comment by exequiel09** [comment]
@BioPhoton was the author of the NgRx versions as well. It's a small subset of what rx-angular has to offer. NgRx versions doesn't have the feature of scheduling work while rx-angular does.

**Comment by exequiel09** [comment]
Also, NgRx version doesn't have the replacement version for `ngFor`. It's named `rxFor`. There's also `rxIf`. those directives apply scheduling in rendering as well. So, I'd say use rx-angular

**Comment by shammy8** [comment]
Are rxFor and rxIf available right now? I installed both the newest versions of the cdk and template packages but can't seem to find either of them. What am I suppose to import to use them?

**Comment by exequiel09** [comment]
@shammy8 it's available right now and we're using `rxFor` in production. `rxIf`.

`rxFor` - `@rx-angular/template/experimental/for`
`rxIf` - `@rx-angular/template/experimental/if`

**Comment by edbzn** [comment]
As @exequiel09 mentioned, `@rx-angular/template` is using a scheduler (forked from the React one) which allows to render tasks things asynchronously

**Comment by edbzn** [comment]
As @exequiel09 mentioned, the main difference between NgRx and RxA is that RxA is internally using a scheduler (forked from React) which renders different parts of the view asynchronously and orders these tasks based on a priority system. It is the piece that ensures that rendering tasks don't take more than 50ms in the browser and keeps your application responsive by splitting the work in a smart way. 

On top of that, RxA brings the concept of [render strategies](https://github.com/rx-angular/rx-angular/blob/main/libs/cdk/render-strategies/docs/README.md), you can see it as a rendering API that let you control the change detection and the priority system in a fine-grained way. These features are performance focused and we think that it is a game changer for RxA.

Let's have a look at the differences between the component-store API:

- with NgRx you have to initialize the state, RxA is built on the concept of lazy state
- with NgRx you cannot pass slices, keys, or operators, RxA `select` has a different signature
- NgRx `select` has no coalescing opt-in, you have to pass a debounce configuration
- NgRx `effect` cannot use a side effect function (closer API to `@ngrx/effect`)
- NgRx `update` cannot connect a source observable to update the state

The component-store is also different in its implementation. RxA made great work at decoupling things. For instance, RxA brings different helpers around the store like:

- [**Effects** to handle side effects and Observable subscriptions](https://github.com/rx-angular/rx-angular/tree/main/libs/state/effects)
- [**Selections** to manipulate the state using reusable tools](https://github.com/rx-angular/rx-angular/tree/main/libs/state/selections)
- [**(wip) Signals** to define actions in a cleaner way](https://github.com/rx-angular/rx-angular/pull/1112)

There are many differences between RxA and NgRx, one last I can expose is the structure of the packages, RxA is split into multiple secondary entry points to benefit from tree-shaking at the best. When you import the `push` pipe into your application, you won't have the `let` directive present in your bundle if you don't use it.

**Comment by LayZeeDK** [comment]
>RxA is split into multiple secondary entry points to benefit from tree-shaking at the best. 
How does multiple package entry points improve tree shaking?

>When you import the push pipe into your application, you won't have the let directive present in your bundle if you don't use it.
This is now the same in NgRx Component: `LetModule` and `PushModule`.

**Comment by LayZeeDK** [comment]
Strange, I thought the build process was intelligent.

**Comment by edbzn** [comment]
Yes UMD is not tree-shakable from my understanding. Note also that we had some part of our code base containing side effects so it was breaking the dead code elimination, cf: https://github.com/rx-angular/rx-angular/issues/805.

**Comment by LayZeeDK** [comment]
Thanks for the reference, that would impact tree-shakability!
