### ISSUE TITLE
The rx-state select/selectSlice doesn't emit until all the state is ready?

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#1413]
# Description

In my code, I have a viewModel that I build from the state:
```
  vm$ = this.state.select(
    selectSlice(['loaded', 'things']),
    map(({ loaded, things }) => ({ loaded, things }))
  );
```
And in my HTML I use this viewModel:
```
 <div *ngIf="vm$ | async as vm">
    <ng-container *ngIf="!vm.loaded">loading...</ng-container>
    <ng-container *ngIf="vm.loaded">{{vm | json}}</ng-container>
   </div>
```
I also have a `subject` action that loads the `things` property (I mock http-requrest):
```
  load = new Subject();

  loadThings$ = this.load.pipe(
    exhaustMap(() =>
      of({ things: [{ id: 1 }, { id: 2 }] }).pipe(
        delay(5 * 1000),
        startWith({ loading: true }),
        endWith({ loading: false, loaded: true })
      )
    )
  );
```
In the beginning, I start with loading: true and end up with loading false and loaded true, and the subject returns things to the store.
In the constructor:
```
   this.state.set({ loaded: null }); // <--- start with null

    this.state.connect(this.loadThings$); // <-- connect the stream to the store
    this.load.next(null);  // <--- start the subject
```

Well, here is the problem:
The `vm` doesn't emit because there are some properties in the store that do not emit at all.
And in this case, I lose the `loading` property..

What if somebody else in my team decides to attach lazy/observable to this store? I'll always lose the loading (until all the observables are complete).

Is it possible to create an operator which gives me the properties although not all of them completely? 

[stackblitz](https://stackblitz.com/edit/angular-ivy-vmnhge?file=src%2Fapp%2Fapp.component.ts)

The fullcode:

```
import { Component, VERSION } from '@angular/core';
import { RxState, selectSlice } from '@rx-angular/state';
import { endWith, of, startWith, Subject } from 'rxjs';
import { map, delay, exhaustMap } from 'rxjs/operators';

@Component({
  selector: 'my-app',
  template: `
   in app!

   <div *ngIf="vm$ | async as vm">
    <ng-container *ngIf="!vm.loaded">loading...</ng-container>
    <ng-container *ngIf="vm.loaded">{{vm | json}}</ng-container>
   </div>
  `,
  providers: [RxState],
})
export class AppComponent {
  vm$ = this.state.select(
    selectSlice(['loaded', 'things']),
    map(({ loaded, things }) => ({ loaded, things }))
  );

  load = new Subject();

  loadThings$ = this.load.pipe(
    exhaustMap(() =>
      of({ things: [{ id: 1 }, { id: 2 }] }).pipe(
        delay(5 * 1000),
        startWith({ loading: true }),
        endWith({ loading: false, loaded: true })
      )
    )
  );

  constructor(
    private state: RxState<{ loading: boolean; loaded: boolean; things: any[] }>
  ) {
    this.state.set({
      loaded: null,
    });

    this.state.connect(this.loadThings$);
    this.load.next(null);
  }
}

```

**Comment by hoebbelsB** [comment]
hey @jon9090 thanks for the issue!!

it was a design decision to skip emitting undefined values. We've even removed undefined as a possible type from the API.
But just having undefined fields in your state won't suppress emission of other values. The problem I see here is that you are trying to `selectSlice` the `things` property, which is undefined and thus `selectSlice` isn't emitting anything.

To fix your problem, simply introduce an initialState like 
```ts
const initialState = { loaded: null; things: [] };
this.state.set(initialState);
```

I hope I could help :)
