### ISSUE TITLE
No documentation for @rx-angular/state + official documentation page does not work

### ISSUE THREAD

**Issue by sarneeh** [rx-angular/rx-angular#1419]
# Description

There's literally no documentation for `@rx-angular/state` and it's very hard to find anything for the other packages as well. The only option I managed to find is to just get into the source code 😭 

# Steps to Reproduce the Issue

- Try any of the documentation links at https://github.com/rx-angular/rx-angular/tree/main/libs/state
- At the [official docs page](https://rx-angular.io/web/state/general/overview), only the `Overview` page works, nothing else

**Comment by bdunni** [comment]
I'd like to +1 this.

**Comment by bdunni** [comment]
If you are in absolute need of the old documentation, you can download the project and go back to a past commit.

**Comment by sarneeh** [comment]
@LayZeeDK Wow! Thank you very much 🙇

**Comment by LayZeeDK** [comment]
@sarneeh
You're welcome! Please keep the feedback coming 

Once #1436 is merged, there will be much more documentation available through the website and additional issues will improve the online documentation including full generated API references (tracked by #1431).
