### ISSUE TITLE
docs: move readme documents from secondary entry points to docs

### ISSUE THREAD

**Issue by LayZeeDK** [rx-angular/rx-angular#1443]
When #1420 has been merged, find every transcluded `README.md` document in a **secondary** entry point, for example `libs/cdk/coercing/README.md` in secondary entry point `@rx-angular/cdk/coercing`.

Move the contents to the document transcluding it, in this case `apps/docs/docs/cdk/coercing/coercing.mdx`.

If there is a partial `_docs.md` document adjacent to it, move its contents into the main document as well, in this case, `coercing.mdx`.

Delete relevant entries from `implicitDependencies` in `nx.json`.

**Comment by mikelgo** [comment]
I would like to pick this up :)

**Comment by LayZeeDK** [comment]
That would be great, @mikelgo! This one is good to go.

**Comment by mikelgo** [comment]
@LayZeeDK can I start with this issue? I'm not sure about the related issue #1420. it seems like the PR for this issue was deleted?

**Comment by LayZeeDK** [comment]
We finally fixed the broken docs build in https://github.com/rx-angular/rx-angular/pull/1445 so that we were able to deploy https://github.com/rx-angular/rx-angular/pull/1439 🙌

Yes, please go ahead with this one, @mikelgo 🙇‍♂️

**Comment by mikelgo** [comment]
Great, I will start with this issue within the next days =)

**Comment by mikelgo** [comment]
Hey @LayZeeDK 
I'm not completely sure if I understood correctly what to do here 😅

So, e.g. looking add `apps/docs/docs/cdk/coercing/coercing.mdx`, I see there: 
```
import Readme, {
  toc as readmeToc,
} from '@site/../../libs/cdk/coercing/README.md';
import Docs, { toc as docsToc } from './_docs.md';
```
--> the readme referenced in the `@site/...` should be moved inside the directory of  apps/docs/docs/cdk/coercing` correct?

**Comment by LayZeeDK** [comment]
@mikelgo
1. Cut the content of `libs/cdk/coercing/README.md` and paste it into `apps/docs/docs/cdk/coercing/coercing.mdx` where the `import Readme, ...` statement is.
2. Delete `libs/cdk/coercing/README.md`.
3. Cut the content of `apps/docs/docs/cdk/coercing/_docs.mdx` and past it into `apps/docs/docs/cdk/coercing/coercing.mdx` where the `import Docs, ...` statement is.
4. Delete `apps/docs/docs/cdk/coercing/_docs.mdx`.

**Comment by LayZeeDK** [comment]
@mikelgo
1. Cut the content of `libs/cdk/coercing/README.md` and paste it into `apps/docs/docs/cdk/coercing/coercing.mdx` where the `import Readme, ...` statement is.
2. Delete `libs/cdk/coercing/README.md`.
3. Cut the content of

**Comment by mikelgo** [comment]
@LayZeeDK PR is open 🙌
