### ISSUE TITLE
chore: pre-commit formatting fix

### ISSUE THREAD

**Issue by aaa123eee** [rx-angular/rx-angular#1453]
# Description

Pre-commit hook doesn't fix formatting

# Steps to Reproduce the Issue

- break a correct formatting
- commit your changes
- create a PR
- see formatting error in the pipeline

**Comment by hoebbelsB** [comment]
hey @aaa123eee thx for the issue. To give some further information for this. We _are_ currently using `lint-staged` and `husky` to setup pre-commit hooks. They should run, but are configured poorly.

this is the current lint-staged setup:

```json
"lint-staged": {
    "libs/**/!(images)/**/*.{ts,html,scss,md,json}": [
      "yarn affected:lint -- --uncommitted --fix --parallel"
    ],
    "libs/**/*.{ts,html,scss,md,json}": [
      "prettier --write"
    ]
  },
```

as u can see, it will only run for files inside the `/libs` folder. We need to change that to reflect all of the files :)

**Comment by hoebbelsB** [comment]
also, the `yarn affected:lint -- --uncommitted --fix --parallel` looks kind of weird because I think `yarn` doesn't require `--` to get arguments.

`prettier --write` probably can be replaced by something like `nx format:write` as well

**Comment by hoebbelsB** [comment]
cc @LayZeeDK

**Comment by LayZeeDK** [comment]
`nx format:write` formats all files that have been changed between the current branch and the default Nx base branch (for example `main`) by default. It should be possible to create a staged format using parameters such as `--uncommitted` and `--untracked` or `--files`, see [the docs](https://nx.dev/nx/format-write#format:write).
