### ISSUE TITLE
chore: investigate redundant build in pipeline

### ISSUE THREAD

**Issue by aaa123eee** [rx-angular/rx-angular#1454]
# Description

Find out why all the PRs want to execute `build`. But `build` is not there anymore. So it's just waiting for something that is never executed

**Comment by hoebbelsB** [comment]
cc @LayZeeDK

**Comment by aaa123eee** [comment]
After investigation, I found out that this is a github's bug. Sometimes workflow isn't deleted after changes

https://github.com/orgs/community/discussions/26256

We can try to toggle it on and off (https://github.com/orgs/community/discussions/26256#discussioncomment-3960320)

**Comment by LayZeeDK** [comment]
@hoebbelsB please review the required checks in repo settings for GitHub Actions. "build" is probably listed as a required check.

**Comment by LayZeeDK** [comment]
Unused job names will be removed after a log retention period has passed.

**Comment by hoebbelsB** [comment]
thx @LayZeeDK you are completely right. Adjusted the setting in the repo and now everything works fine
