### ISSUE TITLE
chore: incorrect codecov report

### ISSUE THREAD

**Issue by aaa123eee** [rx-angular/rx-angular#1455]
# Description

Codecov test coverage reports fail with no reason

# Steps to Reproduce the Issue

- make changes not related to the code itself
- create a PR
- see a coverage decrease report

# Notes

example: https://github.com/rx-angular/rx-angular/pull/1452

**Comment by hoebbelsB** [comment]
cc @LayZeeDK

**Comment by LayZeeDK** [comment]
Sorry, I'm not familiar with Codecov.

**Comment by edbzn** [comment]
Hi, I updated the configuration for Codecov, from what I tested it seems to be correct right now. Feel free to reopen if you notice something unexpected in a coverage report.
