### ISSUE TITLE
Short question about usage and performance

### ISSUE THREAD

**Issue by mariusbolik** [rx-angular/rx-angular#1471]
Hello,

thank you for this great library! 
In our App we often fetch data from various endpoints and we have a very dynamic UI that allows a lot of customizations.
Is there a disadvantage by binding a lot of Behavior Subjects in HTML? Or doesn't it matter how many times the push pipe is used in one html file? Or would it be better to combine all information into one object?

```html
<div class="container" *ngIf="infoText$ | push">
  <h3>{{ (myBoolean$ | push) ? 'Text A' : 'Text B' }}</h3>
  <p>Some text</p>
  <span>infoText$ | push</span>
  <img src="$imageSrc | push"/>
</div>
```

**Comment by hoebbelsB** [comment]
I would also recommend using [`rxLet`](https://www.rx-angular.io/docs/template/api/let-directive) over the `push` pipe and combine everything to one object in your component.
Having that said, you don't have to fear overrendering when binding multiple observables in your template with the push pipe, as kirill already explained

**Comment by mariusbolik** [comment]
@Karnaukhov-kh @hoebbelsB thank you, guys! I appreciate your help!
