### ISSUE TITLE
rxIf - don't resolve a static value

### ISSUE THREAD

**Issue by dawidwitek** [rx-angular/rx-angular#1486]
[](url)Hello,

Maybe it's a bug, maybe I'm doing something wrong. I'll be glad for help :)
I tried to use your library, but sadly I can't get a positive result of using a rxIf with static data.
I tried on stackblitz and in our company app, but sadly I can't go through it.

I'm using versions:
Angular: 14
RXJS: 7.6.0
rx-angular/template: ^1.0.0-rc.4

![Screenshot from 2022-12-22 13-39-09](https://user-images.githubusercontent.com/31903440/209136267-39946617-e011-43a0-81ce-cab4a09ab869.png)

**Comment by hoebbelsB** [comment]
hey @dawidwitek, the `rxIf` directive experienced a big refactoring with the last release (-rc.5). Can u please double check if this is still an issue? I tried it locally and couldn't reproduce on my end.

**Comment by hoebbelsB** [comment]
closing as this is resolved
