### ISSUE TITLE
Dev dependency ng-morph is declared as library's dependency

### ISSUE THREAD

**Issue by ngfx** [rx-angular/rx-angular#1489]
# Description
ng-morph is defined in the dev dependencies of the project, as below:
https://github.com/rx-angular/rx-angular/blob/87488f2a6cbdb20b7e3223b86f31d1f5b5c9ad90/package.json#L117

but it is declared as dependency here:
https://github.com/rx-angular/rx-angular/blob/87488f2a6cbdb20b7e3223b86f31d1f5b5c9ad90/libs/state/package.json#L57

Is it a dependency or dev dependency?
It would be better to correct the dependency declaration here.

# Environment

@rx-angular/state version: 1.7.0 

Angular CLI: 14
Node: 14
OS: win32 x64

**Comment by edbzn** [comment]
Hi @ngfx, it can't be a dev dependency as it's used by rxa to run migrations, it's a dependency as it should be installed on user node_modules, everything seems good to me (except the fact that ng-morph is not well maintained).

**Comment by ngfx** [comment]
Got it. thanks. In this case, I will just follow up with ng-morph for the vulnerability issue.

**Comment by IKatsuba** [comment]
@edbzn we want to renew our contribution to maintaining the `ng-morph`. Stay tuned!

**Comment by edbzn** [comment]
Good to know I have quite some features requests @IKatsuba 😄
