### ISSUE TITLE
docs: fix broken links 

### ISSUE THREAD

**Issue by mikelgo** [rx-angular/rx-angular#1491]
# Description
During the work on #1443 I discovered that some links are broken. These should be fixed in order to have a high-quality documentation.

# Tasks
- [x] Identify and fix broken links, e.g. using https://github.com/tcort/markdown-link-check
- [x] to discuss: include markdown-link-check into CI flow

**Comment by mikelgo** [comment]
I would also take this issue =)

**Comment by edbzn** [comment]
I just noticed that links are not consistent across docs, sometimes it uses `https://www.rx-angular.io` and sometimes `https://rx-angular.io`, maybe this CI check could help to prevent this.

**Comment by mikelgo** [comment]
I also noticed this. 

I'm not sure if the tool is able to do that but I'll investigate.

**Comment by BioPhoton** [comment]
The one inc www as it works without redirects.
In general this is an additional step to configure.

**Comment by mikelgo** [comment]
I started this issue. you can assign it to me if you like =)

**Comment by mikelgo** [comment]
@BioPhoton need your help to fix a broken reference to an img. 

In `apps/docs/docs/cdk/zone-configurations/how-to-debug-zone-flags.md` there is at the botton this image here
`![Sources Tab - Breakpoints](https://raw.githubusercontent.com/rx-angular/rx-angular/main/libs/cdk/zone-configurations/docs/images/dev-tools_sources_breakpoints_michael-hladky.png)`

However it seems to be lost - I can not find it anymore. Do you still have this image? Otherwise I guess we need to remove it so far.

Besides that I fixed every link and inkluded the tool as an automatic check. 
However there's still one problem i need to investigate. Currently the link-checker does report all links to ngrx.io as broken - but they are ok as far as I see.
