### ISSUE TITLE
8 vulnerabilities, when installing RxState

### ISSUE THREAD

**Issue by henrikebbesen** [rx-angular/rx-angular#1493]
# Description

C:\git\testAngular>npm install @rx-angular/state
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
added 84 packages, and audited 98 packages in 34s
18 packages are looking for funding
  run `npm fund` for details
3 high severity vulnerabilities
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
C:\git\testAngular>npm audit
# npm audit report
minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install @rx-angular/state@1.4.6, which is a breaking change
node_modules/ng-morph/node_modules/minimatch
  ng-morph  1.4.0 - 2.1.1
  Depends on vulnerable versions of minimatch
  node_modules/ng-morph
    @rx-angular/state  >=1.5.0
    Depends on vulnerable versions of ng-morph
    node_modules/@rx-angular/state
3 high severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force

# Steps to Reproduce the Issue

ng new testProject
npm install @rx-angular/state
npm audit

# Environment

Angular CLI: 14.2.10
Node: 16.17.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
    "@angular-builders/custom-webpack": "14.0.1",
    "@angular-builders/jest": "14.0.1",
    "@angular-devkit/build-angular": "14.2.10",
    "@angular-eslint/builder": "14.1.2",
    "@angular-eslint/eslint-plugin": "14.1.2",
    "@angular-eslint/eslint-plugin-template": "14.1.2",
    "@angular-eslint/template-parser": "14.1.2",
    "@angular/cli": "14.2.10",
    "@angular/compiler-cli": "14.2.12",
    "@angular/language-service": "14.2.12",
    "@types/jest": "28.1.8",
    "@types/node": "18.11.9",
    "@types/shelljs": "0.8.11",
    "@typescript-eslint/eslint-plugin": "5.42.1",
    "@typescript-eslint/parser": "5.42.1",
    "concurrently": "7.1.0",
    "dotenv": "16.0.3",
    "eslint": "8.27.0",
    "eslint-config-prettier": "8.5.0",
    "headers-utils": "^3.0.2",
    "husky": "7.0.4",
    "jest": "28.1.3",
    "lint-staged": "12.4.1",
    "msw": "0.39.2",
    "post-npm-install": "2.0.0",
    "prettier": "2.7.1",
    "shelljs": "0.8.5",
    "start-server-and-test": "1.14.0",
    "stylelint": "14.8.2",
    "stylelint-config-prettier": "9.0.3",
    "stylelint-prettier": "2.0.0",
    "ts-jest": "28.0.8",
    "ts-node": "10.9.1",
    "typescript": "4.8.4",
    "wait-on": "^6.0.1"
    ```

**Comment by henrikebbesen** [comment]
Sorry 3 iso 8

**Comment by edbzn** [comment]
Hi, the issue comes from `ng-morph` which is used to perform code migration, I'll report the issue in their repo, thanks.

**Comment by edbzn** [comment]
Closing it as it's fixed.
