### ISSUE TITLE
Missing type definitions in template package

### ISSUE THREAD

**Issue by smarlhens** [rx-angular/rx-angular#1508]
# Description

Hey there,

Hope you're doing well.

I was trying to update the [@rx-angular/template](https://github.com/rx-angular/rx-angular/tree/main/libs/template) package to the latest version and noticed something weird - there seems to be no type definitions in the root `index.d.ts` for [1.0.0-rc.5](https://www.npmjs.com/package/@rx-angular/template/v/1.0.0-rc.5?activeTab=explore) and [1.0.0](https://www.npmjs.com/package/@rx-angular/template?activeTab=explore). Is it expected ?

 Content from npm registry (using explore tab) :
<details>

<summary>1.0.0-rc.4</summary>

```typescript
export { UnpatchModule as UnpatchEventsModule, UnpatchDirective, } from '@rx-angular/template/unpatch';
export { LetModule, LetDirective } from '@rx-angular/template/let';
export { PushModule, PushPipe } from '@rx-angular/template/push';
export { ForModule, RxFor, RxForViewContext } from '@rx-angular/template/for';
```

</details>

<details>

<summary>1.0.0-rc.5</summary>

```typescript
export {};
```

</details>

<details>

<summary>1.0.0</summary>

```typescript
export {};
```

</details>

Thanks for helping 🙏🏻 Wish you a great day ☀️

**Comment by edbzn** [comment]
Hi @smarlhens, yes nothing is exported from the main entry point. Symbols are exported in their corresponding secondary entry points, for example in [@rx-angular/template/let/index.d.ts](https://www.npmjs.com/package/@rx-angular/template?activeTab=explore).

**Comment by smarlhens** [comment]
Sure, I noticed that and change my imports in my codebase, thanks

**Comment by edbzn** [comment]
@smarlhens We provided automated migration scripts for this, if you run `ng update @rx-angular/template` or `nx migrate @rx-angular/template` it should migrate the imports.
