### ISSUE TITLE
cdk: coerceObservable is not fully compatible with ObservableInput

### ISSUE THREAD

**Issue by mikelgo** [rx-angular/rx-angular#1516]
# Description
`coerceObservable` takes an argument of type `ObservableInput`, which can be e.g. Promises. 

However the implementation does not take care of e.g. promises (did not check other cases for now) to unwrap them.

The result is that following code: 

```
import { coerceObservable } from '@rx-angular/cdk/coercing';


  constructor() {
    const promise = new Promise((resolve) => resolve(10));

    const obs$ = coerceObservable(promise);

    obs$.subscribe(console.log);
  }

```

results into `ZoneAwarePromise{__zone_symbol__state: true, __zone_symbol__value: 10}`

# Steps to Reproduce the Issue
See Stackblitz https://stackblitz.com/edit/angular-mhrhxh?file=src%2Fmain.ts 

# version
cdk 1.0.0

**Comment by mikelgo** [comment]
I will also open a PR to fix it. Plan is to do this by the weekend =)

**Comment by edbzn** [comment]
Hey @mikelgo, any progress on this? If you need help or you do not have time to make it, let us know! :slightly_smiling_face:

**Comment by mikelgo** [comment]
Hey @edbzn 
no progress so far. Sick wife, child and myself eating up my open-source time :-/ 
If somebody wants to take it up, please go ahead :)

**Comment by edbzn** [comment]
No worries @mikelgo! Hope you get better soon.
