### ISSUE TITLE
Migration cdk from 1.0.0-rc.2 to 2.0.0 stuck forever

### ISSUE THREAD

**Issue by iNViTiON** [rx-angular/rx-angular#1535]
# Description

Expected
After running `yarn ng update @rx-angular/cdk @rx-angular/template -C` the package will properly migrate to 2.0.0 and migration completed without issue.

Actual
After running `yarn ng update @rx-angular/cdk @rx-angular/template -C` the package will properly migrate to 2.0.0 but the migration step freezes up forever. (I leave it overnight and nothing moves.)

![image](https://user-images.githubusercontent.com/13241662/228890541-fa2e3eb8-9cd5-4d14-b09f-89f3a39e98eb.png)

# Steps to Reproduce the Issue

Checked out at this commit.

https://github.com/iNViTiON/StoryPointer/tree/08c682bc41c5a6767297f8632235f1a502846510

Then running this command.

```sh
yarn ng update @rx-angular/cdk @rx-angular/template -C
```

# Environment

```
>yarn ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.2.4
Node: 18.15.0
Package Manager: yarn 3.5.0
OS: win32 x64

Angular: 15.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@angular/fire                   7.5.0
@schematics/angular             15.2.4
rxjs                            7.4.0
typescript                      4.8.4
```

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by iNViTiON** [comment]
> Hi, I just tried and it worked.
> 
> ```
> > yarn ng update @rx-angular/cdk @rx-angular/template -C
> yarn run v1.22.19
> $ ng update @rx-angular/cdk @rx-angular/template -C
> Using package manager: npm
> Collecting installed dependencies...
> Found 24 dependencies.
> Fetching dependency metadata from registry...
>     Updating package.json with dependency @rx-angular/cdk @ "2.0.0" (was "1.0.0-rc.2")...
>     Updating package.json with dependency @rx-angular/template @ "2.0.0" (was "1.0.0-rc.3")...
> UPDATE package.json (1115 bytes)
> ✔ Packages successfully installed.
>   Committed migration step (8ffebc875): Angular CLI update for packages - @rx-angular/cdk@*, @rx-angular/template@*.
> ** Executing migrations of package '@rx-angular/cdk' **
> 
> ▸ Migrate to sub-entry points.
>   Migration completed (No changes made).
>   No changes to commit after migration.
> 
> ** Executing migrations of package '@rx-angular/template' **
> 
> ▸ Migrate to sub-entry points.
>   Migration completed (No changes made).
>   No changes to commit after migration.
> 
> ▸ Migrate rxFor imports from experimental package.
>   Migration completed (No changes made).
>   No changes to commit after migration.
> 
> ▸ Migrate rxIf imports from experimental package.
>   Migration completed (No changes made).
>   No changes to commit after migration.
> 
> Done in 14.62s.
> ```
> 
> It's hard to tell what can cause this without replication.

I forgot to mention that I use Yarn 3 with Volta. If you prefer not to install Volta, you can just config local workspace Yarn 3 by executing `yarn set version stable`.
![image](https://user-images.githubusercontent.com/13241662/228908137-1e8dc681-efe1-4f67-a9a5-3d4a2f10100c.png)

**Comment by edbzn** [comment]
I tried with Yarn 3 but had a couple of peer dependency issues, so I was not able to reproduce. In any case, using different package managers is out of our control, and should not cause a difference in migration execution.

**Comment by iNViTiON** [comment]
@edbzn Based on your run and my reproduction by setting Volta to use Yarn 1.22.19, I believe we can skip that migration as there seems to be no change. Thank you for pointing out the potential issue with Yarn 3, it never crossed my mind.
