### ISSUE TITLE
realworld repos examples?

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#1552]
Do you know of any repositories that provide good examples of using rx-angular and demonstrate best practices? Are you aware of real-world repositories showcasing states, services, and various common issues while providing good examples of using rx-angular and demonstrating best practices?

**Comment by edbzn** [comment]
@jon9090 Best example of real world app that demonstrates good practices is [tastejs/angular-movies](https://github.com/tastejs/angular-movies).
