### ISSUE TITLE
feat(template): viewport and scrolling element separation

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#1555]
# Problem Solved By The Feature

Right now, the `@rx-angular/template/experimental/virtual-scrolling` package only supports the `RxVirtualScrollViewportComponent` to be the scrolling element. However, there are cases where you want to define a separate scrolling element, e.g. to support window scrolling.

# Solution

> Has to be investigated

# Additional Context

This is currently supported by [`@angular/cdk/scrolling`](https://material.angular.io/cdk/scrolling/overview#separate-viewport-and-scrolling-element).

**Comment by lincolnthree** [comment]
Just to add my two cents here. Of all the issues / pending features for this, I think this one is the most critical for my own personal / professional use cases. Scrolling the window is what I need 99% of the time when using a solution like this. I could probably use this virtual-scrolling implementation today if this feature were around.

For some additional thoughts, here's the Angular PR where this was added to the CDK's implementation. I liked their abstraction, but I think it did result in an overly verbose solution. Some middle ground could be found:

https://github.com/angular/components/pull/24394

**Comment by nurfgun** [comment]
Can't wait to see this feature implemented 👍

**Comment by fireonmac** [comment]
I could have used it right away if this feature is implemented. So close!

**Comment by lincolnthree** [comment]
WOOOO!! Yeah lets gooo!!!
