### ISSUE TITLE
trackBy with AutoSizeVirtualScrollStrategy causes item to move after a mutation

### ISSUE THREAD

**Issue by juanfran** [rx-angular/rx-angular#1565]
# Description

Mutate an item while using trackBy in a `AutoSizeVirtualScrollStrategy` scroll, move the mutated element to translateY(0)

![autosize](https://user-images.githubusercontent.com/905195/236183155-3d5b515c-a771-483b-8dd2-357f46d6b75d.gif)

# Steps to Reproduce the Issue

https://juanfran.github.io/rxa-virtual-scroll/#/demos/autosize, wait 2 seconds without moving the mouse.

Commit to reproduce the issue https://github.com/juanfran/rxa-virtual-scroll/commit/b3af8bc2b81bb285aa8b0e7d63f850a3e394cc9d

**Comment by hoebbelsB** [comment]
Thx for the issue. I think this will be fixed with the following PR https://github.com/rx-angular/rx-angular/pull/1562. Sorry for the inconvenience, going to fix it as soon I have some time left!
