### ISSUE TITLE
Angular 16 support (install via npm)

### ISSUE THREAD

**Issue by CharlieGreenman** [rx-angular/rx-angular#1568]
# Problem Solved By The Feature

Able to use Angular 16 (install via npm)

# Solution

Update resolve dependency

# Additional Context
```
npm ERR! Found: @angular/core@16.0.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"16.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^15.0.0" from @rx-angular/template@15.2.0
npm ERR! node_modules/@rx-angular/template
npm ERR!   @rx-angular/template@"15.2.0" from the root project
```

**Comment by Laurens-makel** [comment]
There is already an open PR to implement Angular 16 support.

For further status update please refer to #1567.

**Comment by CharlieGreenman** [comment]
Sorry I search for angular 16 and don't find it

**Comment by Laurens-makel** [comment]
No worries, I am glad that I could point you in the right direction!

**Comment by CharlieGreenman** [comment]
Thank you

**Comment by edbzn** [comment]
@CharlieGreenman We just released v16, thanks for being patient.

**Comment by CharlieGreenman** [comment]
I was quasi-patient. Thank you for this library as always. It greatly improves user experience, makes the application very snappy and I am thankful. Thank you.
