### ISSUE TITLE
Error in entrypoint @rx-angular/state when installing rx-angular/state in Stackblitz

### ISSUE THREAD

**Issue by mikelgo** [rx-angular/rx-angular#1570]
# Description

When installing `rx-angular/state` in a stackblitz project one will get this error: 

```
Error in src/main.ts
The entrypoint for '@rx-angular/state' could not successfully be resolved. The file '/turbo_modules/@rx-angular/state@15.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.
```

I'm not sure if this is an issue with stackblitz or a problem by rx-angular/state. Locally everything is ok.
Nevertheless for ppl who want to e.g. try out a few things before they actually decide to use this lib, it will put a bad light on the lib.

# Steps to Reproduce the Issue
Use this [stackblitz](https://stackblitz.com/edit/stackblitz-starters-12xmyq?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)

Or do the following:
- go to stackblitz.com
- create new angular project
- install `@rx-angular/state@15.0.0` (same error also for version 2.0.0)

**Comment by Mahmoudibrahim03** [comment]
same with me

**Comment by edbzn** [comment]
Should be fixed by https://github.com/rx-angular/rx-angular/commit/958b56f3e8f04946716375e22bcadfc18cac46cc. Thanks for raising this!
