### ISSUE TITLE
missing working examples with stackblitz.com or codesandbox.io

### ISSUE THREAD

**Issue by wizardnet972** [rx-angular/rx-angular#1575]
The example code demonstrating the basic usage of RxState with stackblitz.com or codesandbox.io is not included in the documentation.

I intended to provide my students with code examples showcasing how to use of RxState and let them try, but unfortunately, I am unable to do so online.

I attempted to create my own example, but encountered difficulties that prevented it from functioning correctly. You can find my attempt at the following link: https://stackblitz.com/edit/stackblitz-starters-xdznxh?file=src%2Fmain.ts

**Comment by edbzn** [comment]
Should be fixed by https://github.com/rx-angular/rx-angular/commit/958b56f3e8f04946716375e22bcadfc18cac46cc.
