### ISSUE TITLE
"@rx-angular/template": "^16.0.0" ->  Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by sysmat** [rx-angular/rx-angular#1580]
# Description

- in browser I get error

```
core.mjs:10183 ERROR TypeError: Cannot read properties of undefined (reading 'config')
    at new RxLet (template-let.mjs:379:42)
    at NodeInjectorFactory.RxLet_Factory [as factory] (template-let.mjs:50:12)
    at getNodeInjectable (core.mjs:4658:44)
    at instantiateAllDirectives (core.mjs:11586:27)
    at createDirectivesInstances (core.mjs:11002:5)
    at Module.ɵɵtemplate (core.mjs:15112:9)
    at FootbarComponent_Template (footbar.component.ts:14:5)
    at executeTemplate (core.mjs:10959:17)
    at renderView (core.mjs:12158:13)
    at renderComponent (core.mjs:12105:5)
```

# Steps to Reproduce the Issue

- https://stackblitz.com/edit/stackblitz-starters-62wrjh?file=demo%2Fsrc%2Fapp%2Fapp.component.ts
- in app.component.ts is **RxLet**
- in terminal go to demo folder, `npm i`
- open browser dev console and see error

# Environment

```
Angular CLI: 16.1.0
Node: 18.16.0
Package Manager: npm 9.6.6
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.0 (cli-only)
@angular-devkit/core         16.1.0 (cli-only)
@angular-devkit/schematics   16.1.0 (cli-only)
@schematics/angular          16.1.0 (cli-only)
```

# Tasks to Resolve This

- I don't know

# Notes

- it is regression, it work with @rx-angular:15

**Comment by MarcinBorowski95** [comment]
Same issue here.

**Comment by kinderswan** [comment]
Just had some debugging and noticed that apparently line 
`renderParent = this.strategyProvider.config.parent;`
being executed earlier than constructor.
I wrote simple IIFE to check what's going on and here is the result:
IIFE: 
```
renderParent = (() => {
    console.log(this)
    return this.strategyProvider.config.parent;
})()
```
result:
![image](https://github.com/rx-angular/rx-angular/assets/6896834/64a399e8-8fd4-4c42-8b35-976d244f18a9)

If you try to use ?. operator, the issue starts to happen in other directives

Changing bundler to esbuild gives the same issue

**Comment by kinderswan** [comment]
After half of a day researching it feels the issue somewhere in the build system, like ng-packagr or any deps it uses. Just because I sucessfully ran rx-angular/demos project and also it perfectly works if you copypaste rx-angular libs (cdk/template/state) to your own project

Btw, attaching `parent: false; patchZone: false;` changes nothing

**Comment by edbzn** [comment]
We investigated the issue and found the cause, thanks for raising it and debugging, appreciated! We will release a fix today.
