### ISSUE TITLE
TypeError: this.strategyProvider is undefined

### ISSUE THREAD

**Issue by getlarge** [rx-angular/rx-angular#1582]
# Description

Hi Rx-angular team,
we are currently migrating to Angular 16 and by extensions all the libraries that we use for our Angular apps, and i encountered this issue for the following 3 templates directives:
- RxLet
- RxPush
- RxIf

Maybe the others are concerned but we are not using them and i have not looked at code.

<img width="610" alt="Screenshot 2023-06-22 at 11 54 45" src="https://github.com/rx-angular/rx-angular/assets/15331923/393a6d81-9de0-42f0-83d8-dde0e48ca580">

# Steps to Reproduce the Issue

# Environment

# Related to Other Issues

I suppose those issues are related:
- #1579
- #1580 

# Tasks to Resolve This

This happens because [RxPipe](https://github.com/rx-angular/rx-angular/blob/main/libs/template/push/src/lib/push.pipe.ts#L106) uses a property assignment for `strategyHandler`. Using getter solves the issue but maybe you have reasons against it.
As far as i'm concerned the same would be true with the other template classes:
- [RxLet](https://github.com/rx-angular/rx-angular/blob/main/libs/template/let/src/lib/let.directive.ts) for `renderParent` and `patchZone`
- [RxIf](https://github.com/rx-angular/rx-angular/blob/main/libs/template/if/src/lib/if.directive.ts) also for `renderParent` and `patchZone`

# Notes

**Comment by edbzn** [comment]
Fixed by #1581, thanks for raising the issue.
