### ISSUE TITLE
RxState vs signals?

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#1588]
It's not a bug. 

But I wounder what the benefits of using `RxState` over signals? even RxState will support signals with to use it over normal signal?

**Comment by Laurens-makel** [comment]
I'd like to comment on this to stay in the loop.

I've been using RxState in one of my applications for mainly smart components, whilst signals definitely solves a lot of 'problems' regarding Angular and in particular ZoneJs, we haven't migrated and are highly doubting if required.

We haven't tried signals yet but we like the patterns RxState provides, it gives you some handles to easily manage state and reduce change detection cycles.

Could any of the core maintainers explain not only the benefits, but also the differences between signals and rxstate?

**Comment by hoebbelsB** [comment]
hey, just quickly stepping in here. There won't be any benefit of `RxState` **OVER** `signals`. It's not one or the other, it's more like both in combination. We have created an RFC a while ago when the signals API got introduced, you can take a look here https://github.com/rx-angular/rx-angular/issues/1526.

Long story short, you will benefit from using `RxState` **WITH** `signals` over using plain signals. We plan to seamlessly integrate signals into `RxState` to combine the best of both signals & rxjs.

**Comment by jon9090** [comment]
@hoebbelsB Thank you for the explanation. When will the new version with signals be released?

**Comment by edbzn** [comment]
Closing this, feel free to open another issue if you have other questions.
