### ISSUE TITLE
RFC: funtional `@rx-angular/state` - the new `rxState` function

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#1592]
# Functional building blocks for rx-angular/state

> All changes are non breaking 

RFC based on discussions with: @BioPhoton @eneajaho @ChristopherPHolder @vmasek @Karnaukhov-kh @edbzn @hoebbelsB 

**Documents:**

- rxSignals -   [draft] #1598
- rxActions -   [ready for review] #1593
- rxEffect -   [draft] #1594
- rxState -   [draft] #1526

**Example Repository**
- https://github.com/BioPhoton/rxa-signal-interopt
  - feature 0 - plain Signals
  - feature 0.1 - extended Signals
  - feature 1 - state, effect, action
  - feature 1.1 - state, effect, action + advanced architecture + testing

## Motivation

This PR aims to renew to current API and align with latest Angular features.
It will "modernize" the style of writing and remove old patterns with latest best practices.

A couple of very nice parts of this PR are:
- more lightweight API
- better typing
- reduced bundle size
- removal of provider usage (only needed to have access to ngOnDestroy)
- functional only
- less code

## Examples

Usage in a component

```typescript
import { rxActions } from '@rx-angular/state/actions';

@Component()
export class AnyComponent {
  listApi = inject(ListApi);

  uiSectionA = rxActions<T>({ click: Event });
  uiSectionB = rxActions<{ click: string }>(({transform}) => {
     transform({ click: (e) => e.target.value.toString() })
  });
  
  refreshEffect = rxEffect(this.uiSectionB.click$, () => this.listApi.getAll());
  
  refreshEffect = rxState<list: string[]>();
}
```

### Function as outer API
As we can use `DestroyRef` we can get rid of the DI tick for the `OnDestroy` lifecycle 

**Provider onDestroy**

```typescript
@Component({
    template: `<input (change)="ui.search($event)" />`,
    providers: [ RxAction ]
})
class List Component {
      ui = this.rxActions<A>();

     constructor(private rxActions: RxAction) {
     }
}. 
```

**inject onDestroy**

```typescript
@Component({
    template: `<input (change)="ui.search($event)" />`
})
class List Component {
    ui = rxActions<A>();
}
```

This has the following benefits:
- less boilerplate
- better typing
- flexible API options

### Instances and Classes

We consider 2 layers where we want to respect Angular's DI:

**Provider Level** 

```typescript 
type Actions = { add: Movie }; 

function provideGlobalActions<A>() {
    const GlobalActions = new InjectionToken<A>();
    return { 
        provide: GlobalActions, 
        useFactory: () => rxActions<A>()
    },
}

@Injectable({providedIn: 'root'})
class GlobalActions {
     ui: rxActions(...);
};

const providers = [
    { provide: ErrorHandler, useClass: CustomErrorHandler },
    provideGlobalActions(...),
    // or
    GlobalActions
]
```

**Injection Context Level**

```typescript 
@Component({
    providers: [  { provide: ErrorHandler, useClass: CustomErrorHandler } ]
})
class List Component {
    ui = rxActions<A>();
}
```

This has the following benefits:
- DI available
- scopes provider logic

### Setup function 

We use a setup function instead of static objects. 

```typescript 
// static configuration
// setup here
const cfg = {...};
ui = create(cfg);

// configuration function
ui = create( (setup) => {
  // setup here 
  const cfg = {...};
  setup(cfg);
});
```

This has several benefits:
- lazy evaluation 
- deferred setup possible
- DI available
- full control over execution
- option to encapsulate setup logic 

### Shorthands and naming conventions

**There are:**. 
- `EventEmitter` - lazy initialisation, settable over `emit`
- `Signal` - eager initialisation, settable over `set`
- `Effect` - eager initialisation, implicit subscription over get (`signal()()`)

**You can:**. 
- `define` a `Signal` or `EventEmitter` -  `eventEmitter(effectFn, options)` 
  - `apply` a `behaviour` - async chains `options = { behaviour: debounce }`
  - `derive` with `transforms` - like input transforms `options = { derive: transforms }`
- `create` a `Effect` form a  `defined` a `Signal` or `EventEmitter`
- `react` `on` a `defined` `Signal` or `EventEmitter` notification 
  - with side effect - `signal(0).on(effectFn)`
  - with side effect and effect specific definition  - `signal(0).on(effectFn, { behaviour: debounce, derive: eventValue })`

**Primitives that own a `side effect/react` logic:**
- `signal<T>(v: T, { on: (v: T) => void })` - returns Signal with initialised effect
- `signal<T>(v: T).on((v: T) => void)` - returns void
- `eventEmitter<T>((v: T) => void, { on: (v: T) => void })` - returns void with initialised effect
- `eventEmitter<T>((v: T) => void).on((v: T) => void )` - returns callback to trigger side effect

# How to Release

It is non-breaking for the next release. We just deprecate the factory approach.
In future steps we can write automated migrations and delete the old code base.

0. consider signals in RFC
1. ship primitive without signals
2. feedback from the users
3. implement signals
4. deprecate class based implementation (after feedback is digested)
5. remove class

# To Clarify

- [x] Will there be Classes to use with DI?
- [x] Alignment of new API surface
   - [x] Actions
     - [x] Signals interopt needed? => No as it is about events
   - [x] Effects
      - [x] Signals interopt needed? => There is already a solution for signals in @ angular/core
   - [x] State
      - [x] Signals interopt needed? => Signals for derivations and connections
- [ ] Composition APIs    
   - [ ] Provider Helper 
   - [x] Effect hooks before and after 
   - [x] Effect callback Helper 
      - [x] Signals interopt needed?
   - [ ] Store
      - [ ] Signals interopt needed?

**Comment by hoebbelsB** [comment]
closing as already released
