### ISSUE TITLE
The entrypoint for '@rx-angular/state' could not successfully be resolved. The file '/turbo_modules/@rx-angular/state@16.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#1599]
This error happens in stackblitz (rx-angular/state is v16 with angular v16).

> The entrypoint for '@rx-angular/state' could not successfully be resolved. The file '/turbo_modules/@rx-angular/state@16.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

[stackblitz demo](https://stackblitz.com/edit/stackblitz-starters-vqfnqc?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)

here the code:
```
import 'zone.js/dist/zone';
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';
import { RxState } from '@rx-angular/state';

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule],
  template: `
    <h1>Hello from {{name}}!</h1>
    <a target="_blank" href="https://angular.io/start">
      Learn more about Angular 
    </a>

    {{state | async | json }}
  `,
})
export class App {
  name = 'Angular';

  store = inject(RxState<{ foo: boolean; bar: boolean }>);

  state = this.store.select();
}

bootstrapApplication(App);
```

**Comment by jon9090** [comment]
Hi @edbzn what do you think of it?

**Comment by edbzn** [comment]
Hi @jon9090, it seems that we already had this problem with the v15 cf https://github.com/rx-angular/rx-angular/issues/1570. We rely on ng-packagr for publishing and it's handling the distribution format, so it is related to how Stackblitz is loading it I believe. I'll investigate.

**Comment by wizardnet972** [comment]
@edbzn, in the [package.json](https://github.com/rx-angular/rx-angular/blob/main/libs/state/package.json#L5C7-L5C7) file, the reference to index.js leads to a non-existent file. Turbo relies on this property to locate the entry point. To resolve this issue, my suggestion is to simply create a file named index.ts, and that should fix the problem.

**Comment by edbzn** [comment]
@wizardnet972 Nice catch thank you! What if we remove the "main" property from package.json? I don't see any reason to keep it as ng-packagr should build the correct "exports" entry with linked modules, would that still break Turbo?

**Comment by edbzn** [comment]
Should be fixed by https://github.com/rx-angular/rx-angular/commit/958b56f3e8f04946716375e22bcadfc18cac46cc.
