### ISSUE TITLE
Isr should have the ability to dynamically adjust the key used to store the cache instead of always using the url of the request

### ISSUE THREAD

**Issue by Pii2** [rx-angular/rx-angular#1604]
# Problem Solved By The Feature

If you want to cache a page in different variants on the server side, e.g. a variant for logged-in and non-logged-in users, or for different viewports, this cannot be implemented with one cache per URL.

In such scenarios, the page cached in another variant would lead to a content shift or flickering when loading the page.

# Solution

Provide a factory method that allows to modify the key used to store the cache. 

For example:

```ts
    const isr = new ISRHandler({
        indexHtml,
        invalidateSecretToken: process.env['INVALIDATE_TOKEN'] || 'MY_TOKEN',
        enableLogging: false,
        cacheKeyFactory: (req: Request) => {
            if (req.cookies && req.cookies.access_token) {
                return `${$req.url}%authenticated`;
            }
            return req.url;
        }
    });
```

**Comment by eneajaho** [comment]
@Pii2 I merged the MR from @maxisam which should fix this issue. Closing as completed. Let us know if that one fixes the issue after it gets released.
