### ISSUE TITLE
Push pipe does not work with if it is used within an input

### ISSUE THREAD

**Issue by kevinkasper** [rx-angular/rx-angular#1606]
# Description

I would like to pass an observable of the parent component to a child component in a zoneless application.

For this I use the @rx-angular/template push pipe instead of the native angular async pipe to resolve the observable for the child component input. Unfortunately, the corresponding setter is not called.

If I use the push pipe outside of inputs, the value is rendered correctly.

If I use a separate push pipe to the push pipe of the input, the child component is also rendered correctly.

# Steps to Reproduce the Issue

The problem can be reproduced in the following Stackblitz MVP:

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-guwjvw?file=src%2Fmain.ts)

**Comment by luii** [comment]
The thing thats messing with not displaying the value, but logging is the `delay(1_000)` operator.
From just glancing over i think the Scheduling is messing with you here, `delay` uses `setInterval` on every value greater than 0 (iirc from @BioPhoton 's Talk about Scheduling; a really good source of information btw).

If you remove the delay from the pipe it shows just fine. So thats why i believe that the scheduling on the macrotask (e.g. setInterval) level is wrong and since the application doesnt run change-detection it wont pick up on these changes made on the macro-level. 

I think the push pipes rendering strategy needs to be adjusted for that case (see [here](https://www.rx-angular.io/docs/cdk/render-strategies#features))

**Comment by kevinkasper** [comment]
I tested all rendering strategies in advance and unfortunately no value was rendered with any of them.

I modified the MVP so that a REST call is sent instead of the delay. The same problem occurs here:

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-refnnd?file=src%2Fmain.ts)

**Comment by kevinkasper** [comment]
I have looked at the code and within the `handleChangeDetection` method of the push pipe the `renderedValue` is set correctly.

However, since this is an impure pipe without zone.js, it is not called again, which I believe causes the result to not render.

Does anyone have an idea how to solve this problem?

**Comment by hoebbelsB** [comment]
thx, going to have a look on this

**Comment by hoebbelsB** [comment]
@eneajaho is this maybe a result of your [refactoring](https://github.com/rx-angular/rx-angular/commit/fbdbf5b330334d46319e3790bc78265bd0a2cf74)?

**Comment by eneajaho** [comment]
> @eneajaho is this maybe a result of your [refactoring](https://github.com/rx-angular/rx-angular/commit/fbdbf5b330334d46319e3790bc78265bd0a2cf74)?

Ky refactoring was done for apps to not break when signals were released. Ngrx push pipe and async pipe were changed the same way.

**Comment by hoebbelsB** [comment]
sure, but they don't claim to run outside of zone. Is `untracked` somehow relying on ngzone to be present?

**Comment by eneajaho** [comment]
> sure, but they don't claim to run outside of zone. Is `untracked` somehow relying on ngzone to be present?

From what I've seen it has nothing to do with zone.

**Comment by kievsash** [comment]
Here is playground with untracked removed (I extracted Pushpipe)- still the same issue @hoebbelsB 

[https://stackblitz.com/edit/stackblitz-starters-clw4ml?file=src%2Fclock.service.ts,src%2Fmain.ts,src%2Fpush2.pipe.ts](https://stackblitz.com/edit/stackblitz-starters-clw4ml?file=src%2Fclock.service.ts,src%2Fmain.ts,src%2Fpush2.pipe.ts)

**Comment by kievsash** [comment]
If we just do as in AsyncPipe - add cdr.markForCheck() on assigning/updaing renderValue pushPipe started to work
[https://github.com/rx-angular/rx-angular/blob/16.x/libs/template/push/src/lib/push.pipe.ts#L183](https://github.com/rx-angular/rx-angular/blob/16.x/libs/template/push/src/lib/push.pipe.ts#L183)

const setRenderedValue = this.templateValues$.subscribe(({ value }) => {
      this.renderedValue = value;
      this.cdRef.markForCheck();
    });

Here is analog from Angular 16.2 Asyncpipe
https://github.com/angular/angular/blob/16.2.x/packages/common/src/pipes/async_pipe.ts#L171C1-L171C1

but strange that if I put this.cdRef.detectChanges(); instead- value is not updated

**Comment by hoebbelsB** [comment]
well, this is extremely interesting and I really didn't know. Maybe this behavior is even new :thinking: 

When used as an input, the push pipe get's the CDRef from the ChildComponent. Of course the input cannot be passed, as the parent needs to be checked

![image](https://github.com/rx-angular/rx-angular/assets/4904455/300bc989-42d0-4351-b4c3-865976cdc02e)

**Comment by hoebbelsB** [comment]
**TIL**  When using `inject`, the `CdRef` will be from the ChildComponent. When using constructor based injection, it will be from the ParentComponent.

![image](https://github.com/rx-angular/rx-angular/assets/4904455/c34ed579-f4de-4f24-891c-1c411ff2c0a1)

**Comment by exequiel09** [comment]
Hopefully this can be backported to v16 of `@rx-angular`

**Comment by kkachniarz220** [comment]
any updates here?

**Comment by hoebbelsB** [comment]
inc :)

**Comment by hoebbelsB** [comment]
@kkachniarz220 @exequiel09 @bryanforbes, it's released as template@16.1.2 https://www.npmjs.com/package/@rx-angular/template/v/16.1.2

**Comment by bryanforbes** [comment]
Thank you so much!!!
