### ISSUE TITLE
[Question] why we need to provide RxActionFactory when "new RxActionFactory()" creates encapsulated channels

### ISSUE THREAD

**Issue by andreElrico** [rx-angular/rx-angular#1607]
Sorry for asking a question in the issue world.

Why we need to provide RxActionFactory when "new RxActionFactory()" creates encapsulated channels anyways? It seem like a verbose und not needed measure at first glance.

What is the deeper relevance behind this design choice?

**Comment by edbzn** [comment]
Because the traditional approach in Angular is class-based using DI, we are working on a new functional approach that may interest you, see #1593.
