### ISSUE TITLE
Push pipe seems to loop when observable given by function

### ISSUE THREAD

**Issue by johny1614** [rx-angular/rx-angular#1615]
# Description

We pass an observable to push pipe with such syntax in template: 
`{{selectSomething() | push}}`
Where selectSomething is any function that returns Observable for example:
```
  selectSomething(): Observable<number> {
    return of(5);
  }
```

Actual behavior is that selectSomething is invoked so many times - even when user doesn't interract with the page.
I feel that it shouldn't and it's ok to give push pipe observable from function?

# Steps to Reproduce the Issue

https://stackblitz.com/edit/stackblitz-starters-3ysti1?file=src%2Fmain.ts
You can add logs to selectSomething method to be sure that it's invoked multiple times (but it can freeze ur browser tab)

# Environment

Package                           Version
-----------------------------------------------------------
@angular/animations        16.2.3
@angular/common        16.2.3
@angular/compiler        16.2.3
@angular/core        16.2.3
@angular/forms        16.2.3
@angular/platform-browser        16.2.3
@angular/platform-browser-dynamic        16.2.3
@angular/router        16.2.3
@rx-angular/cdk        ^16.0.0
@rx-angular/template        ^16.1.0
@types/jasmine        4.0.3
rxjs        7.8.1
tslib        2.6.2
zone.js        0.13.1
-->

# Notes
Everything is fine when we make property like
`something$ = this.selectSomething()`
and interpolate it like this:
`{{something$ | push}}
`

**Comment by hoebbelsB** [comment]
this is expected behavior and we cannot really do something about it. Also `rxLet`, `rxIf`, `rxFor` will have the exact same issue. And if I'm not mistaken, the `async` pipe should also have that "issue".

The problem here is that whenever the template is evaluated (aka change detection happens), the function you've bound there is re-evaluated. As the function is always producing a new Observable, `RxPush` will receive a new value to transform. Also an equality check wouldn't help here, as you have provided a entirely new object.

**Comment by johny1614** [comment]
Thanks for quick answer @hoebbelsB  :) 
I felt that it could be misusage but didn't have any warnings, could be easily misused imo.

I've checked all 4 cases - don't have such problem, only push pipe seems to loop endlessly.
If that changes something in terms of technical capabilities. 

[async](https://stackblitz.com/edit/stackblitz-starters-aeuacj?file=src%2Fmain.ts)
[rxLet](https://stackblitz.com/edit/stackblitz-starters-mgc2s7?file=src%2Fmain.ts)
[rxIf](https://stackblitz.com/edit/stackblitz-starters-svcv9c?file=src%2Fmain.ts)
[rxFor](https://stackblitz.com/edit/stackblitz-starters-hkgkbj?file=src%2Fmain.ts)
