### ISSUE TITLE
Streamlining Component Lifecycle Management with RxState and Alternatives

### ISSUE THREAD

**Issue by wizardnet972** [rx-angular/rx-angular#1620]
# Problem Solved By The Feature

Currently, in order to utilize `RxState`, I am required to include it in the component's providers property. This is necessary because I intend to associate RxState with the component's lifecycle. Consequently, when the component is disposed of, the RxState service is also disposed.

However, it's worth noting that there are alternatives available, such as [DestroyRef](https://angular.io/api/core/DestroyRef) or `takeUntilDestroy`. 

If RxState were to utilize these approaches, there would be no need to include it in the component's providers, resulting in cleaner and less verbose code.

# Solution
If necessary, I am willing to submit a pull request (PR).

# alternatives Considered
N/A

# Additional Context

**Comment by hoebbelsB** [comment]
hey @wizardnet972 thank u very much for the feature request. I'm more than happy to tell you this was already in construction and is already merged to the main branch. As soon as we release the next version (should be next days), the new features will be available for everyone.

With the new APIs, we also shipped new docs. Take a [look here](https://www.rx-angular.io/docs/state/setup), as they already show how it will be used.

```ts

import { rxState } from '@rx-angular/state';
import { RxFor } from '@rx-angular/template/for';

@Component({
  template: `<movie *rxFor="let movie of movies$" [movie]="movie" />`,
  imports: [RxFor],
})
export class MovieListComponent {
  private state = rxState<{ movies: Movie[] }>(({ set }) => {
    // set initial state
    set({ movies: [] });
  });

  // select a property for the template to consume
  movies$ = this.state.select('movies');
}

```

**Comment by wizardnet972** [comment]
@hoebbelsB awesome!! You all are doing a great job. Thank you, I really appreciate RxState. I'm looking forward to the release! :)
