### ISSUE TITLE
rxState v16.1.0 in a Service not disposed

### ISSUE THREAD

**Issue by wizardnet972** [rx-angular/rx-angular#1622]
First and foremost, I'd like to express my gratitude for the significant improvements made to DX in the latest changes (v16.1.0).

In my [StackBlitz demo](https://stackblitz.com/edit/stackblitz-starters-a9ojjk), I am utilizing v16.1.0 and attempting to utilize the state in the service.

My objective is to verify whether the state is properly disposed of when the component is destroyed.

Regrettably, it appears that this is not the case, as the timer continues to connect to the store and output data to the console even after the Foo component has been destroyed.

Am I overlooking something in my code?

```
import 'zone.js/dist/zone';
import { CommonModule } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';
import { Component, Injectable, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { rxState } from '@rx-angular/state';
import { tap, timer } from 'rxjs';
console.clear();

export interface Movie {
  id: number;
  name: string;
}

@Component({
  selector: 'foo',
  standalone: true,
  imports: [CommonModule],
  template: `I'm the Foo component {{ movies$ | async | json }}`,
})
export class FooComponent {
  fooService = inject(FooService);

  // Select a property for the template to consume
  movies$ = this.fooService.state.select();

  ngOnInit() {
    console.log('on init');
  }

  ngOnDestroy() {
    console.log('done');
  }
}

@Injectable({ providedIn: 'root' })
export class FooService {
  time = timer(0, 3000).pipe(tap((t) => console.log({ t }))); /// <------------ alive

  state = rxState<{ movies: Movie[]; timer: number }>(({ set, connect }) => {
    set({
      movies: [
        { id: 1, name: 'bla' },
        { id: 2, name: 'bla2' },
      ],
    });
    connect('timer', this.time);
  });
}

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule, CommonModule, FooComponent],
  template: `
    <button (click)="show = !show">Show?</button>
    <foo *ngIf="show"></foo>
  `,
})
export class App {
  show = true;
}

bootstrapApplication(App);
```

Is there something I've overlooked or misunderstood in my code?

**Comment by luii** [comment]
> First and foremost, I'd like to express my gratitude for the significant improvements made to DX in the latest changes (v16.1.0).
> 
> In my [StackBlitz demo](https://stackblitz.com/edit/stackblitz-starters-a9ojjk), I am utilizing v16.1.0 and attempting to utilize the state in the service.
> 
> My objective is to verify whether the state is properly disposed of when the component is destroyed.
> 
> Regrettably, it appears that this is not the case, as the timer continues to connect to the store and output data to the console even after the Foo component has been destroyed.
> 
> Am I overlooking something in my code?
> 
> ```
> import 'zone.js/dist/zone';
> import { CommonModule } from '@angular/common';
> import { bootstrapApplication } from '@angular/platform-browser';
> import { Component, Injectable, inject } from '@angular/core';
> import { RouterModule } from '@angular/router';
> import { rxState } from '@rx-angular/state';
> import { tap, timer } from 'rxjs';
> console.clear();
> 
> export interface Movie {
>   id: number;
>   name: string;
> }
> 
> @Component({
>   selector: 'foo',
>   standalone: true,
>   imports: [CommonModule],
>   template: `I'm the Foo component {{ movies$ | async | json }}`,
> })
> export class FooComponent {
>   fooService = inject(FooService);
> 
>   // Select a property for the template to consume
>   movies$ = this.fooService.state.select();
> 
>   ngOnInit() {
>     console.log('on init');
>   }
> 
>   ngOnDestroy() {
>     console.log('done');
>   }
> }
> 
> @Injectable({ providedIn: 'root' })
> export class FooService {
>   time = timer(0, 3000).pipe(tap((t) => console.log({ t }))); /// <------------ alive
> 
>   state = rxState<{ movies: Movie[]; timer: number }>(({ set, connect }) => {
>     set({
>       movies: [
>         { id: 1, name: 'bla' },
>         { id: 2, name: 'bla2' },
>       ],
>     });
>     connect('timer', this.time);
>   });
> }
> 
> @Component({
>   selector: 'my-app',
>   standalone: true,
>   imports: [CommonModule, CommonModule, FooComponent],
>   template: `
>     <button (click)="show = !show">Show?</button>
>     <foo *ngIf="show"></foo>
>   `,
> })
> export class App {
>   show = true;
> }
> 
> bootstrapApplication(App);
> ```
> 
> Is there something I've overlooked or misunderstood in my code?

I think the problem is that you provide your Service on root level, this service wont be destroyed upon destroying your `Foo` component, try providing the Service inside the Component Providers and remove the `provideIn: 'root'`. This should then yield the expected result and clean up the service.

**Comment by edbzn** [comment]
Hey @wizardnet972, @luii's answer is correct, root services are destroyed only when the app gets destroyed so you should use component providers instead.

**Comment by wizardnet972** [comment]
@luii, indeed, to ensure the state is properly disposed of, it is necessary to connect it to the component lifecycle by including it in the component providers.

However, I was contemplating whether rxState could function without requiring any explicit specification within the providers.

**Comment by edbzn** [comment]
@wizardnet972 You could define the `rxState` directly in the `FooComponent` without using a service, in this case, you don't need to provide anything.
