### ISSUE TITLE
Throwing an error when I run `ng add @rx-angular/template` command on v17 next release

### ISSUE THREAD

**Issue by swami-sanapathi** [rx-angular/rx-angular#1623]
# Description
![image](https://github.com/rx-angular/rx-angular/assets/40539126/26e0b923-4d2b-4022-b058-8b51c48b7758)

# Steps to Reproduce the Issue
Create new repo with latest v17 rc version and run `ng add @rx-angular/template` command

# Environment
Angular CLI: 17.0.0-next.9
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.0-rc.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.9
@angular-devkit/build-angular   17.0.0-next.9
@angular-devkit/core            17.0.0-next.9
@angular-devkit/schematics      17.0.0-next.9
@angular/cli                    17.0.0-next.9
@schematics/angular             17.0.0-next.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0

**Comment by swami-sanapathi** [comment]
Tried with `--force` and `--legacy-peer-deps` as well

**Comment by edbzn** [comment]
Hi, the last @rx-angular/state version is v16.1.0 but it is not officially compatible with Angular v17, ng-add is fetching the v2.0.0 instead because this version had a wider range compatibility. Official support for v17 will come soon.
