### ISSUE TITLE
Use protected injector in RxState

### ISSUE THREAD

**Issue by NicholasVi** [rx-angular/rx-angular#1646]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@rx-angular/state@16.3.0` for the project I'm working on.

I inherit from this class to create components with automatic updates, specifically when certain fields in the state change. To achieve this, I use ɵdetectChanges for automatic change detection. However, since ɵdetectChanges is no longer available in @angular/core, I need to use Injector to get ChangeDetectorRef and call detectChanges().
```
protected connectViewState<K extends keyof T>(keys: K[]): Pick<T, K & keyof T> {
  const sink = {} as Pick<T, K & keyof T>;
  const updateSink$ = from(keys).pipe(
    mergeMap(sourceKey =>
      this.select(sourceKey).pipe(
        tap(sinkValue => {
          sink[sourceKey] = sinkValue;
        })
      )
    )
  );
  concat(this.onInit$, updateSink$)
    .pipe(takeUntil(this.onDestroy$))
    .subscribe(() => {
      -  ɵdetectChanges(this);
      + this.injector.get(ChangeDetectorRef).detectChanges();
    });
  return sink;
}
```
In this code snippet, I'm creating a method connectViewState that automatically connects and updates component data based on changes in specific fields of the state. The ɵdetectChanges method, which was used for change detection, is no longer available directly. Instead, I use Injector to obtain the ChangeDetectorRef instance and manually call detectChanges() to trigger change detection. This ensures that the component is updated when relevant state changes occur.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@rx-angular/state/lib/rx-state.service.d.ts b/node_modules/@rx-angular/state/lib/rx-state.service.d.ts
index 6427444..b76c66c 100644
--- a/node_modules/@rx-angular/state/lib/rx-state.service.d.ts
+++ b/node_modules/@rx-angular/state/lib/rx-state.service.d.ts
@@ -30,7 +30,7 @@ export declare class RxState<T extends object> implements OnDestroy, Subscribabl
     private subscription;
     private accumulator;
     private effectObservable;
-    private readonly injector;
+    protected readonly injector;
     private signalStoreProxy;
     /**
      * @description
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hoebbelsB** [comment]
Hey @NicholasVi, thanks for creating the issue. Isn't it possible for you to just create a new private field for the cdRef? e.g.

```ts
class extends RxState {
  private cdRef = inject(ChangeDetectorRef);

}

```

@edbzn wdyt? I'd have no issues with making the fields inside RxState protected.

**Comment by NicholasVi** [comment]
> Hey @NicholasVi, thanks for creating the issue. Isn't it possible for you to just create a new private field for the cdRef? e.g.
> 
> ```ts
> class extends RxState {
>   private cdRef = inject(ChangeDetectorRef);
> 
> }
> ```
> 
> @edbzn wdyt? I'd have no issues with making the fields inside RxState protected.

Thnx, its work
