### ISSUE TITLE
[ISR] When launching the app with serve:ssr there is an SSR regeneration in front of the cache

### ISSUE THREAD

**Issue by laurentvandelle** [rx-angular/rx-angular#1656]
# Description

When running the app in prod mode with `npm run build:ssr` and then `npm run serve:ssr` the cache is retrieved correctly, but I get a SSR generation on top of it.

I don't have this issue with `npm run dev:ssr`

You can try on this repo : https://github.com/laurentvandelle/simple-isr

## Actual

the app is regenerated on top of the cache

## Expected

the app should keep only the cache and not regenerate on top

# Steps to Reproduce the Issue

1. `npm run build:ssr`
2. `npm run serve:ssr`
3. open http://localhost:4000
4. refresh the page
5. the date should not be updated

# Environment

Node: 16.20.1
Npm: 9.8.1
Angular: 16.2.0
Angular CLI: 16.2.10
OS: MacBook Pro M1 macOS Sonoma v14.1.1 (had the same issue on windows and linux)

**Comment by eneajaho** [comment]
Hello @laurentvandelle 
Sorry for late reply,
In your reproduction, I see that you import the **IsrModule.forRoot()** in the **AppModule**, but that is supposed to be in your **AppServerModule**, as it should be server only. Also as you can see from the import 
`import { IsrModule } from '@rx-angular/isr/server';` 
it ends with server, meaning it is server only code. 

Can you try again and let me know please?

**Comment by laurentvandelle** [comment]
Thanks for your reply, even if it was late :)
Your answer is exact I've just tested and it works !
