### ISSUE TITLE
feat: allow unpatch to unpatch all except specific events

### ISSUE THREAD

**Issue by Laurens-makel** [rx-angular/rx-angular#1663]
# Problem Solved By The Feature

Currently the `unpatch` directive could be used in two ways:

1. Unpatch all events: `<div [unpatch]></div>`
2. Unpatch specific events: `<div [unpatch]='['dragenter', 'dragleave']"></div>`

This works fine, but becomes a bit problematic when you would like to exclude one or two events and unpatch all the others.

One would have to specify all the events, except the ones to exclude.

# Solution

Ideally one could write the following, which would imply that all events except `dragover` and `mouseover` should be unpatched.

`<div [unpatch]="['!dragover', '!mouseover']"></div>`

# Alternatives Considered

Specifying the entire list of events except the ones I do not want unpatched.

# Additional Context

In our app we render a lot of `<input>` fields, we noticed that alot of DOM events would trigger change detection on these fields. For example hovering, clicking, dragging over, whatever event would happen, would cause a CD cycle.

We decided to add `[unpatch]` but this had the side effect that a lot events such as `blur` and `change` would not trigger the `FormControl.valueChanges` observable to emit.

To solve this we would have to specify all the other events to the unpatch directive except these ones.

The docs show the following warning:
![image](https://github.com/rx-angular/rx-angular/assets/37303445/77414699-23ce-4eed-8e6a-c83fcc89c4db)

Shouldn't there be a warning to for when the above situation applies?

```
Warning: Do not use [unpatch] on elements that reference a FormControl. Specify all events (for now) except the `blur` and `change` events. Otherwise user input is ignored, the FormControl.valueChanges observable will not emit and attached validations to the FormControl will not run until next change detection that affects the component in which the element is rendered.
```

**Comment by BioPhoton** [comment]
We could think of another option.

Some negation maybe. Do you have an idea of how the API could look like?

**Comment by Laurens-makel** [comment]
> We could think of another option.
> 
> Some negation maybe. Do you have an idea of how the API could look like?

What about the initial draft in #1668 ?

**Comment by Laurens-makel** [comment]
@hoebbelsB  @BioPhoton
Update regarding the additional context:

Turns out that a directive was applied to all rendered input fields, this directive provides additional functionality to by automatically padding/unpadding a desired character till a desired length. The user could type `123` and it would get padded to `0000000123` when the user has left the input field and would get unpadded to `123` again on `focus` and `mouseenter` .

I've made a quick reproduction repository in which this behaviour is demonstrated. In this example I cannot get the `.valueChanges` observable to stop emitting by only applying the `unpatch` directive. When I have some time again I'm going to dig deeper in the application where this occurred and under which circumstances this happens. 
https://github.com/Laurens-makel/unpatch-formcontrol

For now I'd like to propose to revise the changed docs in #1665 to describe that the events used by HostListeners of applied directives should probably be unpatched.

**Comment by Laurens-makel** [comment]
> @hoebbelsB @BioPhoton Update regarding the additional context:
> 
> Turns out that a directive was applied to all rendered input fields, this directive provides additional functionality to by automatically padding/unpadding a desired character till a desired length. The user could type `123` and it would get padded to `0000000123` when the user has left the input field and would get unpadded to `123` again on `focus` and `mouseenter` .
> 
> I've made a quick reproduction repository in which this behaviour is demonstrated. In this example I cannot get the `.valueChanges` observable to stop emitting by only applying the `unpatch` directive. When I have some time again I'm going to dig deeper in the application where this occurred and under which circumstances this happens. https://github.com/Laurens-makel/unpatch-formcontrol
> 
> For now I'd like to propose to revise the changed docs in #1665 to describe that the events used by HostListeners of applied directives should probably be unpatched.

@hoebbelsB @BioPhoton 
To elaborate on this, I have updated the reproduction repository again.

The key factors here are:

1. FormControls with attached Validator functions
2. Directives that provide `@HostListener` event listeners for the `mousedown`, `mouseenter`, `mouseleave`, `mousemove`, `mouseout`, `mouseover`, `mouseup` are problematic for change detection by nature.
3. If `[unpatch]` is applied to any input element that has a binding with a `FormControl` and a directive with specified events applied, change detection problems are solved for the problematic events. However a new problem is introduced, the binding with the `FormControl` is only updated when change detection runs.

There are multiple solutions to that:

1. Run change detection on blur, CD runs and `FormControl` binding is updated once the user left the input field.
2. Run change detection on input, CD runs and `FormControl` binding is updated on every input event the user triggers, basically every character typed.

I've observed in the example where all events are unpatched, the directive that provides the `@HostListener` still succesfully (un)pads the value and updates the `FormControl` binding as well, without running any change detection.

My hypothesis here is that we could provide a generic directive which listens to `input` events, updates the value binding with the `FormControl` instance and only if the validity has been changed, mark the component for change detection.

This way we can still provide feedback regarding the validity of the value directly to the user whilst typing but we are avoiding a change detection cycle on every input event and only call change detection once the validity has changed and we need to inform the user about the change.

What do you guys think?

**Comment by hoebbelsB** [comment]
@Laurens-makel can we close this after your contribution?
