### ISSUE TITLE
Importing `@rx-angular/cdk/zone-configurations` produces bundles with 2 imports of @angular/core which results to bundle size jump

### ISSUE THREAD

**Issue by exequiel09** [rx-angular/rx-angular#1670]
# Description

Importing `@rx-angular/cdk/zone-configurations` produces bundles with 2 imports of @angular/core which results to bundle size jump. It's now both imported in `main` and `polyfills`

Before: 

![image](https://github.com/rx-angular/rx-angular/assets/1289472/473043ad-7bff-49e1-bdbc-25b250101e79)

After:

![image](https://github.com/rx-angular/rx-angular/assets/1289472/34e4eef2-cc6c-4081-af5a-53e7c3f5fd93)

# Steps to Reproduce the Issue

Just follow the instructions here: https://www.rx-angular.io/docs/cdk/zone-configurations/how-to-setup-zone-flags

# Environment

Angular v17
RxAngular v17

**Comment by vmasek** [comment]
I just seen a same issue in project, I don't think it is related to RxAngular, more to actual action of having custom polyfills file.

It appeared as I created separate custom polyfills file instead of just having the angular's `zone.js` default.

In `project.json` change 
from: `"polyfills": ["zone.js"],`
to: `"polyfills": ["zone.js", "apps/my-app/src/polyfills.ts"],`

and as soon as there is import to `@angular/core` in the polyfill or it's dependency, it will produce this bundle.

for me it was just simple `globalThis.process.env` patch

```
import { isDevMode } from '@angular/core';

if (!globalThis.process?.env) {
  globalThis.process = {
    ...globalThis.process,
    env: {
      mode: isDevMode() ? undefined : 'production',
    },
  };
}
```

**Comment by exequiel09** [comment]
> I just seen a same issue in project, I don't think it is related to RxAngular, more to actual action of having custom polyfills file.
> 
> It appeared as I created separate custom polyfills file instead of just having the angular's `zone.js` default.
> 
> In `project.json` change from: `"polyfills": ["zone.js"],` to: `"polyfills": ["zone.js", "apps/my-app/src/polyfills.ts"],`
> 
> and as soon as there is import to `@angular/core` in the polyfill or it's dependency, it will produce this bundle.
> 
> for me it was just simple `globalThis.process.env` patch
> 
> ```
> import { isDevMode } from '@angular/core';
> 
> if (!globalThis.process?.env) {
>   globalThis.process = {
>     ...globalThis.process,
>     env: {
>       mode: isDevMode() ? undefined : 'production',
>     },
>   };
> }
> ```

Where should be this patched? I think this needs to be documented somewhere in the docs site? 🤔

**Comment by edbzn** [comment]
I made a test with and without zone-configurations to compare bundle content and I can confirm that RxA zone-configurations duplicates the `@angular/core` module.

**With zone-configurations**:

[stats.json (esbuild)](https://github.com/rx-angular/rx-angular/files/13874888/stats.json)
![with-zone-flags](https://github.com/rx-angular/rx-angular/assets/8522558/8a87f6b3-d146-4300-8dc7-dfbc05a9e67d)

Import of `ɵglobal` in `@rx-angular/cdk/zone-configurations` results in importing the module `node_modules/@angular/core/fesm2022/core.mjs` (1.5kb) in the polyfill bundle, we can see it in the bottom right corner of the treemap. 

**Without zone-configurations**:

[stats.json (esbuild)](https://github.com/rx-angular/rx-angular/files/13874961/stats.json)
![without-zone-flags](https://github.com/rx-angular/rx-angular/assets/8522558/d8bf52a2-9638-4929-90f4-ff2e40dbf251)

No extra `@angular/core` import resulting in the polyfill bundle.

Here's the [repo used](https://github.com/edbzn/rxa-zone-configurations-issue).

Knowing that under the hood `ɵglobal` is defined like:

```ts
const _global = globalThis;
export _global as ɵglobal;
```

We should get rid of it now.
