### ISSUE TITLE
RxVirtualScroll do not fill empty space when an item in the viewport changes position (sorting the array)

### ISSUE THREAD

**Issue by Lougnar** [rx-angular/rx-angular#1679]
Hi, 

# Description

When the array provided to *rxVirtualFor is sorted, space left by items in viewport that changed positions are not filled. If the user scroll down to push the empty space out of the viewport and scroll up, the space disapear and the items are displayed correctly

# Steps to Reproduce the Issue

I made a minimal repoduction of the bug: 
https://stackblitz.com/edit/stackblitz-starters-izzuwy?file=src%2Fmain.ts

Click on the button below the virtual scroll, the item 2 will be repositionned at the end of the array. You will see a space between item 1 and item 3.

# Environment

Tested on "@rx-angular/template": "16.1.1", + Angular 16 and "@rx-angular/template": "17.0.1" and Angular 17

# Note

I haven't found a workaround at the moment

Best regards,
Lougnar

**Comment by hoebbelsB** [comment]
thanks for the issue and sorry for the delay. Going to investigate this week :crossed_fingers:
