### ISSUE TITLE
[State] select default transform fn

### ISSUE THREAD

**Issue by kkachniarz220** [rx-angular/rx-angular#1683]
# Problem Solved By The Feature
```typescript
this._state.select(['foo', 'bar'], s => s) // { foo, bar }
```

To

```typescript
this._state.select(['foo', 'bar']) // { foo, bar }
```
Probably the most common way of use `select(keys: K[])` is to transform to a simple object with same data structure as in state.

# Solution
Make default mapping in `select(keys: K[])`

**Comment by AdrianRomanski** [comment]
@hoebbelsB I would like to take this one :)
