### ISSUE TITLE
ISR cache invalidation error

### ISSUE THREAD

**Issue by moddi3** [rx-angular/rx-angular#1687]
# Description 

I'm using angular 17 with the new release of @rx-angular/isr. Everything is working well except on-demand invalidation, when I trigger localhost:4000/api/invalidation I'm getting this error - `ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: 'api/invalidate'`
Either you trigger it via the postman or via the button - the result is the same.
It's also noteworthy that the http request answers 200.

@eneajaho help, please

# Steps to Reproduce the Issue
https://codesandbox.io/p/devbox/divine-pine-mq2vq7

when you click the **invalidate** button you will see error in console
<img width="818" alt="image" src="https://github.com/rx-angular/rx-angular/assets/11387313/208f2b88-4ac4-4183-a263-cdb1d838f3c6">

# Environment

```
Angular CLI: 17.1.2
Node: 18.19.0
OS: macOS Sonoma / codesandbox

Angular: 17.1.2
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
```
<img width="551" alt="image" src="https://github.com/rx-angular/rx-angular/assets/11387313/a01dfe54-b79c-47f1-9c00-2868971fc2f0">

**Comment by moddi3** [comment]
> Hello @moddi3 I just tried with a simple example https://github.com/rx-angular/rx-angular/pull/1688/files and everything worked fine.
> 
> ![CleanShot 2024-02-08 at 15 10 35@2x](https://private-user-images.githubusercontent.com/25394362/303361207-240750fb-2a04-49c2-833b-e88b38c0a485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDI1NjksIm5iZiI6MTcwNzQwMjI2OSwicGF0aCI6Ii8yNTM5NDM2Mi8zMDMzNjEyMDctMjQwNzUwZmItMmEwNC00OWMyLTgzM2ItZTg4YjM4YzBhNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE0MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzVjMjVlMDM4OTAzYmE2NjI2OTg3NDg3YmJkNzdiZDk1Y2RhOGI4ZjA4MTdhODQzZjg0N2E3MjUxZTI1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32ZBeyLwfNFfGlx3cuYJ1-1CnDIlhbpcK8x9xPAUdlI)
> 
> Do you also get these issues locally?

yes, locally I have same error
also I deployed my example project to vercel and this problem is there too
so, I don't understand if it's a problem with the environment or what.

**Comment by eneajaho** [comment]
The errors says that's something else problem and not something from ISR side, but express or critters side. 

I'll check it again.

**Comment by eneajaho** [comment]
Hello @moddi3 
After another check, I couldn't find the issue. Looks like a specific version of the critters libs has an issue (not 100% sure about that)

Can you make sure your imports are correct? And you're following all the steps of the getting started guide? https://www.rx-angular.io/docs/isr/getting-started

**Comment by moddi3** [comment]
> Hello @moddi3 After another check, I couldn't find the issue. Looks like a specific version of the critters libs has an issue (not 100% sure about that)
> 
> Can you make sure your imports are correct? And you're following all the steps of the getting started guide? https://www.rx-angular.io/docs/isr/getting-started

Hi @eneajaho , now I also think that the problem is not with the ISR library but with my local dependencies. I will investigate further and comment on this issue when I find a solution. 
At this point, I think we can close this issue. Thank you for your help!

**Comment by moddi3** [comment]
Hi, @eneajaho. 
I got to investigate why my invalidation wasn't working and I reproduced this bug in the rx-angular repository. 
The whole point is the **wildcard route**, if I remove it (and my project didn't have it at the time I created the issue), I get an error - `ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: 'api/invalidate'`, a screenshot of which I attached at the very beginning of this thread. With wildcard route - everything works. 

Can you reproduce this at your place? I used node v20 inside your project.

<img width="940" alt="image" src="https://github.com/rx-angular/rx-angular/assets/11387313/62fcb67c-d8b2-4409-b3cf-f38c9e1bc810">
<img width="1196" alt="image" src="https://github.com/rx-angular/rx-angular/assets/11387313/e9c743b7-b003-405f-a098-0ac5286f6712">

**Comment by eneajaho** [comment]
Hello @moddi3 
Thanks for the investigation. Will get back at this when I get some free time. 
I also reopened the issue.

**Comment by jginorio** [comment]
I experienced exactly the same thing. When I saw that Angular was throwing an error that it couldn't find the path for "api/invalidate," I thought it was making an HTTP request to Angular using that path. So, I checked the ISR code to see how the invalidate function worked and noticed it used a function called "renderUrl." Within that function, I saw a series of steps to modify the "req.url," and I observed that when using the "commonEngine," the "req.url" wasn't being modified. This resulted in Angular trying to render the path for "api/invalidate."

Therefore, I modified the URL to pass the path of the params as the function comment suggested, and this resolved the error. Below, I will put the code to better explain what I did.

**This is the code where I modified the commonEngine URL**

```javascript

// helper method that generates html of an url
const renderUrl = async (options) => {
    const { req, res, url, indexHtml, providers, commonEngine, bootstrap, browserDistFolder, } = options;
    const { protocol, originalUrl, baseUrl, headers } = req;
    // we need to override url of req with the one we have in parameters
    req.url = url;
    req.originalUrl = url;
    const BASE_URL_PROVIDER = {
        provide: APP_BASE_HREF,
        useValue: baseUrl,
    };
    return new Promise((resolve, reject) => {
        const allProviders = providers
            ? [...providers, ...EXTRA_PROVIDERS] // if providers are provided, we add them to the list
            : [...EXTRA_PROVIDERS, BASE_URL_PROVIDER]; // if not, we add the default providers
        if (commonEngine) {
            let $URL = `${protocol}://${headers.host}${req.url}`;
            console.log($URL)
            commonEngine
                .render({
                bootstrap,
                documentFilePath: indexHtml,
                url: $URL,
                publicPath: browserDistFolder,
                providers: [...allProviders], // we need to cast to StaticProvider[] because of a bug in the types
            })
                .then((html) => {
                resolve(html);
            })
                .catch((err) => {
                reject(err);
            });
        }
        else {
            res.render(indexHtml, { req, providers: allProviders }, async (err, html) => {
                if (err) {
                    reject(err);
                }
                resolve(html);
            });
        }
    });
};

```



**THIS IS THE ORIGINAL CODE WHERE THE commonEngine URL stays with the orignalURL**

```javascript

const renderUrl = async (options) => {
    const { req, res, url, indexHtml, providers, commonEngine, bootstrap, browserDistFolder, } = options;
    const { protocol, originalUrl, baseUrl, headers } = req;
    // we need to override url of req with the one we have in parameters
    req.url = url;
    req.originalUrl = url;
    const BASE_URL_PROVIDER = {
        provide: APP_BASE_HREF,
        useValue: baseUrl,
    };
    return new Promise((resolve, reject) => {
        const allProviders = providers
            ? [...providers, ...EXTRA_PROVIDERS] // if providers are provided, we add them to the list
            : [...EXTRA_PROVIDERS, BASE_URL_PROVIDER]; // if not, we add the default providers
        if (commonEngine) {
            commonEngine
                .render({
                bootstrap,
                documentFilePath: indexHtml,
                url: `${protocol}://${headers.host}${originalUrl}`,
                publicPath: browserDistFolder,
                providers: [...allProviders], // we need to cast to StaticProvider[] because of a bug in the types
            })
                .then((html) => {
                resolve(html);
            })
                .catch((err) => {
                reject(err);
            });
        }
        else {
            res.render(indexHtml, { req, providers: allProviders }, async (err, html) => {
                if (err) {
                    reject(err);
                }
                resolve(html);
            });
        }
    });
};

```
```

I hope this helps

**Comment by moddi3** [comment]
Hi, @jginorio. Can you make a pull request with these changes?

**Comment by jginorio** [comment]
> Hi, @jginorio. Can you make a pull request with these changes? 

Hey!

Sure, I haven't done this before, so I'll review the documentation on how to contribute and then create the pull request. I'll aim to have it done by the end of this week.

**Comment by moddi3** [comment]
Nice! Happy to help if you need any help later on.

> > Hi, @jginorio. Can you make a pull request with these changes?
> 
> Hey!
> 
> Sure, I haven't done this before, so I'll review the documentation on how to contribute and then create the pull request. I'll aim to have it done by the end of this week.

**Comment by eneajaho** [comment]
Thanks @jginorio and @osnoser1 . This fix should be released soon.
