### ISSUE TITLE
The request was not cached with FileSystemCacheHandler

### ISSUE THREAD

**Issue by moaabd** [rx-angular/rx-angular#1690]
# Description

when i use FileSystemCacheHandler and i want to cache a page with path like : /offre-emploi?salary=true.
I have an error Error: 💥 The request was not cached!
It work with simple path like :  /offre-emploi but not with query param.

I try to use the default CacheHandler, and it work well.

 const fsCacheHandler = new FileSystemCacheHandler({
        cacheFolderPath: join(serverDistFolder, '/cache'),

        prerenderedPagesPath: serverDistFolder,
        addPrerenderedPagesToCache: false,
    });

    const isr = new ISRHandler({
        indexHtml,
        invalidateSecretToken: 'MY_TOKEN', // replace with env secret key ex. process.env.REVALIDATE_SECRET_TOKEN
        enableLogging: true,
        serverDistFolder,
        browserDistFolder,
        buildId: 'test',
        cache: fsCacheHandler,
        bootstrap: AppServerModule,
        commonEngine,skipCachingOnHttpError: false,
    });

# Expected
the page /offre-emploi?salary=true. must be cached like in InMemoryCacheHandler

# Environment

SSR
Node: 20.9.0
Npm: 10.1.0
Angular: 17.0.3
Angular CLI: 17.0.1

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by eneajaho** [comment]
Hello,
ISR doesn't support query params for the moment 

This is the function that converts your route to filename and it only supports path params. 
Can you rename this issue to: 
`feat: add support for query params in ISR FileSystemCacheHandler`
Thanks.

https://github.com/rx-angular/rx-angular/blob/d94bb6b3d95c95652aa9e7a47ba51394c0458940/libs/isr/server/src/cache-handlers/filesystem-cache-handler.ts#L342

**Comment by smartsuhani** [comment]
I've same issue regarding the cache handling, please take a look [here](https://github.com/rx-angular/rx-angular/issues/1647#issuecomment-1945345085), thanks.

**Comment by eneajaho** [comment]
> I've same issue regarding the cache handling, please take a look [here](https://github.com/rx-angular/rx-angular/issues/1647#issuecomment-1945345085), thanks.
Hello @smartsuhani 
Are you using the FilesystemCacheHandler? Are you passing query params in the URL? Is this the case?

**Comment by maxisam** [comment]
@eneajaho I add a commit to handle this one as well.
