### ISSUE TITLE
Virtual Scroll: New data not rendered when scrolling fast

### ISSUE THREAD

**Issue by KevinBelien** [rx-angular/rx-angular#1698]
# Description
When scrolling rapidly through data, especially when scrolling upwards quickly, new data is not getting fetched. The current implementation involves checking if the last message is rendered by the virtual scroller upon "scrolledIndexChange". However, despite this check, new data retrieval does not occur as expected. Is there a better way to achieve this?

I also created a [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-vbicoi)

# Steps to Reproduce the Issue

1. Open StackBlitz
2. Scroll very fast to top or press "scroll to top" button.

**Current behavior:**
new data is not being fetched fast enough to keep up with rapid scrolling. This results in the following problems: Incomplete Data, Confusing User Experience

**Expected result:**
You are able to scroll smoothly to top and all messages will be fetched without having to scroll down and up again. When all messages are fetched, a message will appear confirming that all messages have been retrieved.

**EDIT**
Further to my earlier report, I've observed an issue with scrolling behavior. The scrollposition exhibits unexpected jumps upon upward scrolling when starting from bottom, impacting the overall user interaction.

**Comment by KevinBelien** [comment]
Is there any update regarding this topic?

**Comment by hoebbelsB** [comment]
will have a look asap, sorry for the delay

**Comment by hoebbelsB** [comment]
hi @KevinBelien I am looking into this issue at the moment and it looks like the virtual scroller has problems when prepending data to the top of the list in that scenario.
Seems to be an issue with the scroll position that is not properly adjusted. Going to investigate further and hopefully come up with a fix for it.

**Comment by KevinBelien** [comment]
Thanks for the update. Keep me posted.

**Comment by hoebbelsB** [comment]
hey @KevinBelien I've created a PR that introduces a new flag to support reverse infinite scrollers as yours. The PR also contains a new demo which showcases the flag with an implementation very close to your example. Could you please check that out? :)

**Comment by KevinBelien** [comment]
Hey @hoebbelsB, I've been testing the demo and it seems to be working great! The reverse infinite scrolling functionality works just like expected.

**Comment by hoebbelsB** [comment]
just released it with template 17.3
