### ISSUE TITLE
✘ [ERROR] Could not resolve "node:path" at /rx-angular-isr-server.mjs:2:21:

### ISSUE THREAD

**Issue by TomieAi** [rx-angular/rx-angular#1699]
# Description

It works on `ng serve` but not on ` ng build` or I just dont know how to build? how you build this thing XD

I keep getting

```js
✘ [ERROR] Could not resolve "node:fs"

    node_modules/@rx-angular/isr/fesm2022/rx-angular-isr-server.mjs:1:20:
      1 │ import * as fs from 'node:fs';
        ╵                     ~~~~~~~~~

  The package "node:fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


✘ [ERROR] Could not resolve "node:path"

    node_modules/@rx-angular/isr/fesm2022/rx-angular-isr-server.mjs:2:21:
      2 │ import { join } from 'node:path';
        ╵                      ~~~~~~~~~~~

  The package "node:path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

```

I don't know what to change because below this site  [https://www.rx-angular.io/docs/isr](https://www.rx-angular.io/docs/isr) 

it says

![image](https://github.com/rx-angular/rx-angular/assets/111332073/d9a1b260-4b5b-492d-8804-fde9cdaf54b5)

```"node:path"``` should be not an issue due to ```server.ts``` have it 
```import { dirname, join, resolve } from "node:path";```

### this error is so specific on rx-angular-isr-server.mjs xD thats why i'm confused.

# Steps to Reproduce the Issue

clone and build this fresh project [https://github.com/TomieAi/isr-test-app](https://github.com/TomieAi/isr-test-app)
# Environment

```
Angular CLI: 17.2.3
Node: 20.11.1
Package Manager: yarn 1.22.21
OS: linux x64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cli                    17.2.3
@angular/ssr                    17.2.3
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```
# Related to Other Issues

NOPE

# Tasks to Resolve This

XD NO IDEA

# Notes

Hmm yeah I can't build it and I think i followed the tutorial nice enough from here 
[```https://www.rx-angular.io/docs/isr/getting-started```](https://www.rx-angular.io/docs/isr/getting-started)

### I feel I'm forgetting something I just don't know what xD but if you clone my project 
[https://github.com/TomieAi/isr-test-app](https://github.com/TomieAi/isr-test-app)
i feel i did read it the tutorial properly i dont know please correct me  <3 
I really need this to work. this is the 1st time im working on ssr.  I wanna move my old project to ssr/isr base.  

```ng new isr-test-app --minimal --ssr --standalone --skip-tests --skip-install```

**Comment by TomieAi** [comment]
fu*k i think i confused this two xD hahah 
```
app.config.server.ts
app.config.ts
```

aaaa

**Comment by cskiwi** [comment]
@TomieAi What was "the thing" you put in the wrong place ? because I'm having the same issue as you are having. however it looks like I configured everything correctly

**Comment by troquatte** [comment]
I also did it wrong, register in app.config.server.ts and not in app.config.ts
