### ISSUE TITLE
rxState `asReadOnly`

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#1703]
# Problem Solved By The Feature

right now, if you have e.g. a service with a global state:

```ts
class Service {
  state = rxState();
}
```

everyone using `Service` also has full access to its state. 
This is a problem as you don't want others to write into your state.

If you want to expose only slices, you have to provide a public property per slice:

```ts
class Service {
 private  state = rxState();

 slice$ = this.state.select('slice1');
 slice2$ = this.state.select('slice2');

}
```

# Solution

To have a more convenient way to share a read only access to your state, we could introduce a `asReadOnly` function on top of `RxState` which only exposes `select` & `get`

```ts

class Service {
 private  _state = rxState();

 state = this.state.asReadonly();

}
```

**Comment by AdrianRomanski** [comment]
@hoebbelsB if its free i can do it :D

**Comment by hoebbelsB** [comment]
Sure! Thank u for contributing ❤️
