### ISSUE TITLE
Can't install eslint-plugin on Nx v18.2

### ISSUE THREAD

**Issue by exequiel09** [rx-angular/rx-angular#1707]
# Description

Nx 18.2 uses `@typescript-eslint/eslint-plugin` v7.4 and the ESLint plugin uses v6.10 https://github.com/rx-angular/rx-angular/blob/e05f377023d1d5e81f2eda84f88288dca78ab663/libs/eslint-plugin/package.json#L7

# Steps to Reproduce the Issue

Just create a new Nx monorepo and the installation will fail

# Environment

Nx: 18.2
Angular: 17.3

# Notes

The RxAngular monorepo might need some Nx upgrade also.

**Comment by hoebbelsB** [comment]
we'll have a look asap, thx

**Comment by exequiel09** [comment]
Workaround for now is to stay use `6.21.0` which is still supported in v18.3 of Nx https://github.com/nrwl/nx/blob/581ede1486a197f08704c8e8cb7fefe45e8ba45d/packages/eslint-plugin/package.json#L27

**Comment by hoebbelsB** [comment]
thank u from reminding me again @exequiel09 . Does this https://github.com/rx-angular/rx-angular/pull/1715 fix the issue?

**Comment by exequiel09** [comment]
> thank u from reminding me again @exequiel09 . Does this #1715 fix the issue?

@hoebbelsB looks good. i can now install without peer deps issue.

**Comment by exequiel09** [comment]
Hello @hoebbelsB  I see releases for [state](https://github.com/rx-angular/rx-angular/releases/tag/state%4017.2.0) and [template](https://github.com/rx-angular/rx-angular/releases/tag/template%4017.2.0). 

Hopefully, we can release new version of the ESLint package. Thanks 🙏🏻 

cc @edbzn

**Comment by hoebbelsB** [comment]
@exequiel09 done, sorry for letting you wait

**Comment by exequiel09** [comment]
Thanks @hoebbelsB 💯 🙏🏻
