### ISSUE TITLE
Rx Template - RxLet, RxFor, RxIf

### ISSUE THREAD

**Issue by talgershman** [rx-angular/rx-angular#1716]
In angular 17 we have a new code flow.

I was wonder what is the best practice if I was using Rx Template utils.

So I remove them and use the 'native' angular ngFor, ngIf ...etc. what will give me best preformnace ?

Is there a way to use Rx Template utils in the new code flow syntax ?

Thx,
Tal

**Comment by hoebbelsB** [comment]
hey @talgershman ,

there is no best practice guide for this. You can mix and match both approaches as it fits your use cases. If you care about performance (especially bootstrap / creation), the `@rx-angular/template` directives will always be beneficial. But it's also not best practice to e.g. use `rxLet` in every components template. Use it where it fits.

The new control-flow doesn't bring that much of a performance boost compared to the old approach. The one metric where it really improved is swapping rows (see https://blog.angular.io/introducing-angular-v17-4d7033312e4b).

> Is there a way to use Rx Template utils in the new code flow syntax ?

Sadly there isn't and we can't do much about it. This is a 100% internal thing of the angular framework and no 3rd party (e.g. also angular material) cannot implement features using the new control flow. As soon as this changes, we will 100% migrate to it.
