### ISSUE TITLE
Question - Is it possible to only handle the false case via *rxIf?

### ISSUE THREAD

**Issue by friendlyAce** [rx-angular/rx-angular#1718]
# Description
Hi, i just very recently discovered this project and i'm currently migrating to it.
I have a question regarding the opposite of this show$ example.
https://www.rx-angular.io/docs/template/api/rx-if-directive#:~:text=Context%20Variables%20on%20else%20template
![image](https://github.com/rx-angular/rx-angular/assets/79854554/c198d621-b1e2-4085-a395-065c4e98f09d)

Lets say we have a hidden$ observable instead, and only if this evaluates to false ('shown'), we want to display a div with content
`public readonly hidden$ = of<boolean>(false);`

Before Rx-Angular
`<div *ngIf="(hidden$ | async) === false">displayed if !hidden</div>`

With *rxIf with only an else template
```
<ng-container *rxIf="hidden$; else showTemplate"></ng-container>
<ng-template #showTemplate>
  <div>displayed if !hidden</div>
</ng-template>
```
With wrapping the observable value via rxLet
```
<ng-container *rxLet="hidden$; let hidden">
  <div *rxIf="!hidden">display if !hidden</div>
</ng-container>
```

Or for example when you only want to render something if the data has a certain minimum length
`*rxIf="(array$ | push)?.length > 12"`

[Demo](https://stackblitz.com/edit/angular-15-starter-pack-infoas?file=src%2Fapp%2Fapp.component.html)
Is there any possibility do this with rxIf, to evaluate the if expression based on the value of the observable?
Or is this the way to go (if inversion the observable is not an option)?
`<div *rxIf="(hidden$ | push) === false">display if !hidden</div>`

**Comment by hoebbelsB** [comment]
sadly it's not supported natively. You could create a `NegateObservablePipe` to do the job for you, e.g.


```ts

@Pipe({ name: 'negate', standalone: true })
export class NegatePipe {
  transform(v$: Observable<any>) {
    return v$.pipe(map(v => !v ));
  }
}
```

use it in the template:

```html

<div *rxIf="hidden$ | negate"></div>

```

But this adds a bit of mental overhead when parsing the template manually.


Also, I want to mention that you should not use `rxLet` and `rxIf` like that 

> With wrapping the observable value via rxLet

> ```html
> <ng-container *rxLet="hidden$; let hidden">
>  <div *rxIf="!hidden">display if !hidden</div>
> </ng-container>
> ```

As `rxLet` is already scheduling the value updates, you don't need `rxIf` to do the same. It's fine to use `ngIf` in that case :)

**Comment by friendlyAce** [comment]
Hi @hoebbelsB, 
i would like to further understand, when to prefer the ng directives over the rx directives and what common pitfalls there are.

So based on your reply, i noticed that the template "drop in replacement" do not mean a "find and replace all occurrences", e. g. always go from ngIf to rxIf, | async to push, etc. as i originally thought.

But i might not yet fully understand why exactly that's the case and when to avoid rx directives and when not to and when to combine rx directives and when to combine ng directives and rx directives, i would appreciate some examples or clarification.

Understanding the limitations or situations where traditional Angular directives and bindings are more appropriate would be extremely helpful.
It would also be very helpful if there was something in the documentation, especially for people who do not yet have much experience with rx-angular, to display some real-world examples, with some explaination even maybe, why some code example / usage is a bad practise, especially for migrating to rx-angular.

From what i have understand with your comment is, that
if an observable is already provided via rxLet, rxIf or rxFor, we should avoid using another rx directive on the value derived from that rx directive?
And instead use an ng directive, to not cause any re-scheduling?


BR

**Comment by hoebbelsB** [comment]
hey @friendlyAce thanks you for the feedback. We definitely need a section in the docs and/or blog posts covering this topic in particular. I'm going to create a new issue out of it and try to take care of it soon.
