### ISSUE TITLE
Upgrade to Angular 18

### ISSUE THREAD

**Issue by Akxe** [rx-angular/rx-angular#1729]
# Problem Solved By The Feature

Ability for anyone else to upgrade to Angular 18

# Solution

Upgrade Angular and NX

# Alternatives Considered

Angular could be added as `devDependency` making upgrade to higher version possible (with unknown results...)

# Additional Context

none needed

**Comment by hoebbelsB** [comment]
on it

**Comment by Akxe** [comment]
Sorry to make this dumb issue, but I did not find a PR to keep track in :)

Thanks for the good work you and your team have done :)
