### ISSUE TITLE
ISR: Invalidating cache does not allow to modify

### ISSUE THREAD

**Issue by sihu** [rx-angular/rx-angular#1742]
# Description

I was two sided if this is a issue or a feature request. Feel free to change. I noticed a diverging behaviour when invalidating. Before suggesting changes, I wanted to ensure that I understood it correctly and my assumptions are correct:

* when adding a key first time to the cache it calls `renderUrl` and if given modifies the content (e.g. https://github.com/rx-angular/rx-angular/blob/main/libs/isr/server/src/isr-handler.ts#L257-L263) and add this modified html to the cache: https://github.com/rx-angular/rx-angular/blob/main/libs/isr/server/src/isr-handler.ts#L284
* when invalidating the cache, it will also call the `renderUrl` but without modifiying since this cannot be specified in the config (e.g. https://github.com/rx-angular/rx-angular/blob/main/libs/isr/server/src/isr-handler.ts#L284) and add the generated html (without the same modifications) to the cache (e.g. https://github.com/rx-angular/rx-angular/blob/main/libs/isr/server/src/isr-handler.ts#L119)
* when serving from cache, we can also pass a `modifyCachedHtml` which would be applied to the response to the (maybe already modified) cache value. This might be wanted to modifiy it further .

I would expect that the cache content is generated the same way as the first call. Therefore I'd suggest these changes:

* `InvalidateConfig` should also have a `modifyGeneratedHtml` and apply it before adding it to the cache
* applying the `modifyGeneratedHtml` should maybe be part of `renderUrl` so they cannot diverge. 
* using `invalidate` as used on https://www.rx-angular.io/docs/isr/on-demand-revalidation would not behave the same i

The easiest approach for me would be to add the `modifyCachedHtml` and do the same change as i do on `modifyGeneratedHtml` but i think this is not so intuitive. If this would be a Handler-Config and not a config on the function, the usage would be simpler.

# Steps to Reproduce the Issue

* specify a `modifyGeneratedHtml` and make a notable change (a big `h1` at the beginning)
* call a site and put it to cache
* call `invalidate` to the site you just cached
* expect the notable change not to be there anymore

# Tasks to Resolve This

To be discussed. Either add the `modifyGeneratedHtml` to `InvalidateConfig` or change the interface.

**Comment by maxisam** [comment]
@sihu I just push a commit with the same thought as you. (I actually didn't read your issue closely first, but end up with the similar thought). I tracked it here #1758, you can link to the commit from https://github.com/rx-angular/rx-angular/issues/1758#issuecomment-2316688701. Feel free to give any feedback
