### ISSUE TITLE
Virtual scroll: Resetting items to an array smaller than currently rendered range results in component crash

### ISSUE THREAD

**Issue by rozpuszczalny** [rx-angular/rx-angular#1744]
# Description

When a virtual scroll has items and is not scrolled to the top, and items get reset to an array smaller than currently rendered, a TypeError is thrown, making a component unusable.

The issue is observed for autosize and dynamic strategies - fixed strategy seems to work just fine.

```
TypeError: Cannot read properties of undefined (reading 'size')
    at _AutoSizeVirtualScrollStrategy.getItemSize (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1942:38)
    at _AutoSizeVirtualScrollStrategy.calcAnchorScrollTop (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1907:36)
    at Object.next (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1620:14)
```

# Steps to Reproduce the Issue

## Reset to empty array

**See stackblitz:**

- [dynamic strategy](https://stackblitz.com/edit/stackblitz-starters-ggjmb8?file=src%2Fmain.ts)
- [autosize strategy](https://stackblitz.com/edit/stackblitz-starters-435szr?file=src%2Fmain.ts)

**Steps:**

1. Enter page
2. Scroll (or click on the "scroll to 100" button)
3. Click on the "reset items" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

## New items array is smaller

It is possible to encounter the issue when new items array is smaller than currently rendered range. See [this stackblitz](https://stackblitz.com/edit/stackblitz-starters-bsuszv?file=src%2Fmain.ts) and follow reproduction steps:

1. Enter page
2. Scroll to the bottom (or click on the "scroll to 5" button)
3. Click on the "set to 1 item" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

# Environment

@rx-angular/template 17+ . Stackblitz has version 18, but in our codebase we observe the same issue with rx-angular version 17.

# Notes

`getItemSize` throws, when an `_virtualItems` array is empty, or an `index` is out of bounds. First part to fix it is probably to add an optional operator. Another part is calling `getItemSize` when `index` is definitely not present there, but I'm not sure how you want to tackle that.

```ts
  getItemSize(index) {
    return this._virtualItems[index]?.size || this.tombstoneSize;
  }
```

**Comment by hoebbelsB** [comment]
thanks, taking a look

**Comment by rozpuszczalny** [comment]
I've added one more scenario, as this issue not only happens when the items array is reset to an empty array, but also when the items array is smaller than a currently rendered range. Therefore, a proposed workaround does not solve the issue. See [this stackblitz](https://stackblitz.com/edit/stackblitz-starters-bsuszv?file=src%2Fmain.ts) and follow reproduction steps:

1. Enter page
2. Scroll to the bottom (or click on the "scroll to 5" button)
3. Click on the "set to 1 item" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

**Comment by rozpuszczalny** [comment]
Hey, I've added PR with a simple `?.` fix. From my testing, it looks like a viewport component works just fine with that fix.

**Comment by hoebbelsB** [comment]
released the fix with template@18.0.1

**Comment by rozpuszczalny** [comment]
@hoebbelsB thanks! Any chance for a fix release for 17.3.x? 😁

**Comment by hoebbelsB** [comment]
haha, let me see what I can do. Why don't u just upgrade to v18? :D

**Comment by rozpuszczalny** [comment]
Well, we have few dependencies that are not supporting Angular 18 just yet, so we need to hold upgrading from 17 to 18. _(Also last update to 17 took a bit of time and we needed to shift the focus on features for some time 😅 )_
