### ISSUE TITLE
ISR: Redis CacheHandler

### ISSUE THREAD

**Issue by maxisam** [rx-angular/rx-angular#1754]
# Solution

Add a redis cache handler to support storing cache in redis 

# Additional Context

Not sure if you want to add this feature to this repo. If you think it is a good idea, I will make a PR for it.

**Comment by eneajaho** [comment]
Hi, because most of the time cache handling is a bit custom depending on the project, we have only added it in the docs https://www.rx-angular.io/docs/isr/cache-handlers#custom-cache-handler

**Comment by maxisam** [comment]
didn't realize you already have it there. Thanks for pointing out
