### ISSUE TITLE
ISR: Render behaves differently between render / regenerate / invalidate

### ISSUE THREAD

**Issue by maxisam** [rx-angular/rx-angular#1758]
# Description

only render has feature for `modifyGeneratedHtml`, it is missing from the other two

I think the issue here is we should consolidate the render function a bit more.

also with modifyGeneratedHtml, I think there is no need for `cacheMsg` in InMemoryCacheHandler

We can have a default `modifyGeneratedHtml` function just like cacheMsg 

# Notes

I will try to fix this in my fork, if you like the proposed solution, I will make a PR.

Sorry making a bunch of changes in a short time, I am trying to port our existing feature to this library. My goal is trying to match the upstream as much as possible.

**Comment by eneajaho** [comment]
Yes, that would be great! Thanks for doing all this! I will make sure to review and merge everything!

**Comment by maxisam** [comment]
Thanks! Your library is really awesome. 

So my current plan is rename regeneration to generation and add another param for different mode, since they actually behave a little different. But I might change my mind after working on this a bit more. 

I plan to do this one first and then #1755 



Welcome to give me any suggestion.

**Comment by maxisam** [comment]
I think we shouldn't have 2 different configs to modify the html for serveFromCache and render

https://github.com/rx-angular/rx-angular/blob/3f919167f68a1bc969e95876d81a4dbace306fc1/libs/isr/models/src/isr-handler-config.ts#L127

https://github.com/rx-angular/rx-angular/blob/3f919167f68a1bc969e95876d81a4dbace306fc1/libs/isr/models/src/isr-handler-config.ts#L110

I understand the need to have a way to serve different variant of a page, but  variants to do that already.

with 2 different configurations, 

we have to provide render config here

https://github.com/rx-angular/rx-angular/blob/3f919167f68a1bc969e95876d81a4dbace306fc1/libs/isr/server/src/isr-handler.ts#L209-L217

If we only allow one config for that, we can just add providers and modifyCachedHtml to ISRConig and use the ISRConfig for everything.

Any thought?

**Comment by maxisam** [comment]
Actually, I think I can still preserve modifyCachedHtml in ServeFromCacheConfig to avoid breaking change.

But I think we have to add modifyGeneratedHtml in ISRHandlerConfig

**Comment by maxisam** [comment]
I created a commit to show the idea. I will test it more tomorrow but I think it should work. It does change a lot of code so feel free to give me some feedback.

**Comment by maxisam** [comment]
this is done
