### ISSUE TITLE
Slack invite is invalid

### ISSUE THREAD

**Issue by aloksharma1** [rx-angular/rx-angular#1774]
go to repository footer and click on slack link, it gives message:

This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

i wanted to ask a few questions in community, more like a discussion but this and discord both links are non-working.

**Comment by michalgrzegorczyk-dev** [comment]
duplicated: https://github.com/rx-angular/rx-angular/issues/1770
