### ISSUE TITLE
rxVirtualFor does not display anything for a valid initialScrollIndex and items that fit in a single page

### ISSUE THREAD

**Issue by zarko-tg** [rx-angular/rx-angular#1779]
# Description

One cannot always know the number (or total height) of list items for display in advance. I have a case where I'd like to set the initialScrollIndex to a valid value, but all items fit on screen / in a single page.
This results in a blank page - there are no items rendered in the DOM at all.

The expectation is at least that the items get displayed.

# Steps to Reproduce the Issue

https://stackblitz.com/edit/stackblitz-starters-eq5ehz?file=src%2Fmain.ts

This works out of the box for the purpose of the demo/reproduction, but once you set the number of items to for. ex. **10** (so they should all fit in one page) the problem occurs.

# Environment

Angular CLI: 18.2.4
Node: 20.17.0
OS: macOS 15.0

Angular: 18.2.x
Ivy Workspace: Yes
@rx-angular/template: 18.2.0

# Workaround

Not aware of any straightforward workaround.

**Comment by hoebbelsB** [comment]
Thanks for the issue, will investigate over the weekend!
