### ISSUE TITLE
Global and local strategies configuration

### ISSUE THREAD

**Issue by Karnaukhov-kh** [rx-angular/rx-angular#184]
# Things to discuss

## General
- How we should setup global strategies? Global Service vs InjectionTokens.
- What are pros and cons of Global Service & InjectionTokens?
- How Global Service and InjectionTokens should behave with lazy-loaded modules?
- _Registering custom strategies (?)_
## Configuration granularity
- **Global level**. Global Service or InjectionTokens will behave the same.
- **Lazy loaded features**. Custom service/token instance vs global instance.
- **Component level**. Planned RxRenderer can be used.
- **Let, ViewportPrio, RxRenderer & Push**. Planned RxRenderer can be used.
 - **Change at the run time**. What should we use? RxRenderer/another service?

**Comment by LayZeeDK** [comment]
As I see it, it's not a question of class-based service vs. injection token. All tokens used for dependency injection can be overridden. From the perspective of a consumer, class-based service vs. injection token only differ in that we need to consumer injection tokens using `@Inject(injectionToken)` in our constructor.

We can make it easy to set up Angular module-scoped configurations by exposing Angular modules using the `forRoot/forChild` (or `forFeature`) pattern.

**Comment by BioPhoton** [comment]
tokens are not changeable at runtime. This is one difference I would like to spotlight.

**Comment by LayZeeDK** [comment]
@BioPhoton 
Please explain run-time switching of dependencies.

**Comment by BioPhoton** [comment]
Hi @LayZeeDK 

I can't set the default strategy to another value at run time if I use tokens.

**Comment by LayZeeDK** [comment]
Still not getting it. Looking for code snippets to demonstrate the two approaches.

**Comment by hoebbelsB** [comment]
Imo there is no need to change a "default" config at runtime since every component (`Let`, `Push`, ..) can be configured via parameters at runtime.
I think it boils down to personal preference if you like using `@Inject()` or not. It should make no functional difference at all because users always have the possibility to provide their own instances of `Services` or `InjectionToken` with different configurations on any module level. Or do I miss something essential here?

**Comment by BioPhoton** [comment]
> Imo there is no need to change a "default" config at runtime since every component (Let, Push, ..) can be configured via parameters at runtime.

We thought about this will help to switch the config of a whole component insted of applying all the extra syntax in the template.

> I think it boils down to personal preference 
Technically there is a difference in changing things at runtime.

**Comment by LayZeeDK** [comment]
Really curious about this "changing things at runtime".

**Comment by BioPhoton** [comment]
So the default strategy e. g. Can be configured over a token once. At runtime you can't change thst value once initialized the service.

If the service would have a set method you can change that setting also at runtime.

**Comment by LayZeeDK** [comment]
Thanks, now I get it 😊

**Comment by BioPhoton** [comment]
Close as it needs a redesign
