### ISSUE TITLE
Rename `master` to `main` branch

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#204]
Todos:
- [ ] https://dev.to/rhymu8354/git-renaming-the-master-branch-137b
- [ ] github actions
- [ ] https://github.com/BioPhoton/rx-angular/pull/237#discussion_r471076804

**Comment by Karnaukhov-kh** [comment]
Russian podcast where this issue was mentioned: https://www.youtube.com/watch?v=t-BIofputoE&t=1848s

**Comment by Karnaukhov-kh** [comment]
Some guide: https://jarv.is/notes/github-rename-master/
Official doc: https://github.com/github/renaming

**Comment by BioPhoton** [comment]
Nice https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

This looks promising! Let's see how much later this year it will happen :D

**Comment by BioPhoton** [comment]
Will close until automation is in place
