### ISSUE TITLE
Experiment with css `content-visibility`

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#208]
Experiment with css `content-visibility`.

- [ ] How it works
- [ ] Is there a possible combination of viewport-prio
- [ ] ...

**References:**
- [blog](https://web.dev/content-visibility)
- [spec](https://drafts.csswg.org/css-contain-2/#content-visibility)

**Comment by SerkanSipahi** [comment]
@BioPhoton I will take this one :)

**Comment by BioPhoton** [comment]
Hi  @SerkanSipahi Any updated on this?

**Comment by BioPhoton** [comment]
Hi @Karnaukhov-kh as you did some research, could you put that info somewhere in readme so we can close this one?
In best case, we have a rout under experiments in the demos app.

**Comment by Karnaukhov-kh** [comment]
Sure, will create something :)
