### ISSUE TITLE
Autogenerate API docs

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#234]
# Problem Solved By The Feature

No manual steps needed for generating the API docs.

# Solution

* add `yarn generate-typescript-docs` to the generate docs github action.
* adopt output paths for generated docs (maybe need to touch jsDocs of the files).
`libs\state\docs`
`libs\template\docs`
* remove "artefacts" from generated docs pages

**Comment by BioPhoton** [comment]
Maybe we PR to https://github.com/timdeschryver/docs-md and use this one?

**Comment by BioPhoton** [comment]
Any progress? 
Did we decide what we want to do here? This is major requirement for an automated release task.

**Comment by BioPhoton** [comment]
Any progress?

**Comment by BioPhoton** [comment]
Jo! Just want to check back here... 
any news? :D
