### ISSUE TITLE
Why is this project not included in ngrx?

### ISSUE THREAD

**Issue by christianacca** [rx-angular/rx-angular#243]
So I think that @rx-angular/template sources were at some point _cloned_ to become @ngrx/component. Whereas @rx-angular/state is a _competitor_ to @ngrx/component-store. 

**Questions**
1. Why is the ngrx team incorporating (a cloned) @rx-angular/template but have chosen to adopt another solution for local component state?
2. Is there going to be synergy in the form of shared code/ideas between @rx-angular/state and @ngrx/component-store
3. What advice should be given to the community when deciding between making a choice between @ngrx/component-store and @rx-angular/state
4. Is the intent that @ngrx/component will work with @rx-angular/state now and in the future.

btw, thanks for all the hard work you guys are putting in. I really felt uneasy with the trend to promote local component state to a global store. Your solution really satisfies a real practical need that was missing for a long time.

**Comment by Waterstraal** [comment]
Also curious about this.

**Comment by Sam-Lin-MillersLab** [comment]
I actually have the same question. I wonder why we don't join force with ngrx?
