### ISSUE TITLE
Array-set insert 

### ISSUE THREAD

**Issue by pheara** [rx-angular/rx-angular#301]
Posting this at the suggestion/request of @BioPhoton 

# Problem/Context

Working on a small code snippet[1] managing an array of unique id, at the request of @BioPhoton I tried solving it using the transformation helpers from `@rx-angular/state`. `remove` works well for this. During the refactoring we weren't sure whether `insert` would just append the second array or -- as the name could suggest for some -- treat the array as set. Generally it does suggest a stateful/in-place operation for me, instead of the pure function it is.

[1]: 
```
    selectedGuids: string[] = [];
    selectItem(guid: string, selected: boolean) {
        if (selected) {
            const s = new Set([...this.selectedGuids, guid]);
            this.selectedGuids = Array.from(s);
        } else {
            this.selectedGuids = remove(this.selectedGuids, [guid]);
        }
    }
```

# Suggestions That Might Be Interesting

- rename `insert` to `append`/`concat`/etc to make it clearer it's pure
- add an (unique)insert/merge function that treats the array as set

It's really suggestions though and I'd only add the set-insert/merge if you'd actually use it in your codebase.

**Comment by BioPhoton** [comment]
close  in favor of #392
