### ISSUE TITLE
State 1.5.0

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#310]
✍️ Feature:
- [x] #293
- [x] #301
- [x] #419  

🐞 Fix:
- [x] 📚 #269
- [ ] 📚 #358
- [ ] 📖 📚 #311

**Comment by hoebbelsB** [comment]
what about `select` vs `selectSlice` ?

**Comment by BioPhoton** [comment]
I though that the scope is big and we move it into 1.6.0. And maybe do prepreational refactorings in 1.5.

**Comment by hoebbelsB** [comment]
okay, but I think the `selectSlice` in general is more useful and will save TONS of lines of code. this is highly subjective though

**Comment by BioPhoton** [comment]
We can switch feature a d do that in 1.5 and effect in 1.6...
