### ISSUE TITLE
Some minor docs improvements.

### ISSUE THREAD

**Issue by andreElrico** [rx-angular/rx-angular#313]
# Some problems in the docs.

```
@Component({
  selector: 'app-root',
  template: `
    <ng-container *rxLet="hero$; let hero; strategy: 'local'">     <!<!<! it makes sense to write strategy: strategy or remove the class property
      <app-hero [hero]="hero"></app-hero>
    </ng-container>
  `
})
export class AppComponent {
  strategy = 'local';
}
```
and 

```
<button [unpatch] <!<!<! there is something missing (click)="triggerSomeMethod($event)">click me</button>
<button
  [unpatch]="['mousemove']"
  (mousemove)="doStuff2($event)"
  (click)="doStuff($event)"
>
  click or hover me
</button>
```
# Sorry for this informal discussion but ...
As this is all about performance wouldnt it be wise to use strings and omit template bindings?

`<button unpatch="['mousemove, mousedown']"`

then in unpatch directive use `JSON.parse()`.

**Comment by kajetansw** [comment]
Thanks for the feedback!

1. You are right, will fix that.
2. If I understand correctly, you mean there is an array of values missing? In case there is no value bound to the `UnpatchEventsDirective` it takes a default list of the `zonePatchedEvents` (see [this file](https://github.com/rx-angular/rx-angular/blob/master/libs/template/src/lib/experimental/unpatch/events/unpatch-event-list.ts) to the complete list), so using it just as `[unpatch]` in the template is OK.
3. I believe we could do that, but in case of passing string and then parsing it internally to an array we:
- lose any editor and compiler support in case we've bound a wrong type. Input binding expects type of `string[]` and any other would result in error, which we would get in runtime. With proper typing we get that information instantly with a help of the IDE (or at the compile time),
- lose compiler support in case someone makes a typo when trying to write a string in a proper format, e.g. `['mousedown, 'mouseup']`.

**Comment by andreElrico** [comment]
Thanks for the fast reply :-)

2. I would not use `[unpatch]` alone as `[]` is ment for template bindings. But I would assume you want to point out to the reader that `[unpatch]` is the directive of focus.

3. Yes, agree on that. If that lands someday https://github.com/microsoft/TypeScript/issues/6579 it will be super interesting to have it as a string.
