### ISSUE TITLE
Fix Slack Link

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#327]
Discuss if we should use:
https://discord.com/channels/748677963142135818/756545030184894527

**Comment by kajetansw** [comment]
@BioPhoton @hoebbelsB @Karnaukhov-kh 
As a possible solution, I saw that the Elm homepage uses https://github.com/rauchg/slackin for sending out Slack invitations.

Link to their server: https://elmlang.herokuapp.com
