### ISSUE TITLE
Demo Application for @rx-angular

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#330]
## Description

We need a demo application showcasing every feature of `@rx-angular/template` + giving insights how and where it is providing performance benefits over the core `AsyncPipe`.

We already have an `experiments` app running, where we can re-use at least something.

### plain features
  - [x] push
  - [x] unpatch
  - [x] let
     -  [x] templates (S / N / E / C)
  - ~~let vs push (what's the difference?)~~
  - ~~strategies~~
     - ~~local~~
     - ~~detach~~
     - [x] noop?
     - ~~global + native (lowest prio)~~
  - [x] usage of render-callback
  - [x] rxFor/rxSwitch/....
  - [x] viewport-prio
  - [x] global render queue

### performance section
  - ~~**DONTS** or common performance pitfalls~~
  - ~~push vs async~~
  - [x] let  
      - [x] async vs let (*ngIf hack)
      - [x] render deeply nested, ....
      - [x] more examples please
  - [x] rxIf vs ngIf
  - [x] rxSwitch vs ngSwitch
  - [x] rxFor vs ngFor
  - [x] global render queue vs local rendering

### Other

* ~~go all in with ng-universal + PWA? :O~~ postponed
* [x] multiple builds? (zoneless / zonefull)
* [x] CI pipeline for automated build/deploy
* [x] are we able to host multiple versions of the same app on github pages?
* [x] do we need another branch/PR for the development?
* [x] re-use `experiments app` remove not needed demos
* [x] harmonize menu/routing imports
* [x] should we use @rx-angular/state inside demos?

**Comment by BioPhoton** [comment]
Hi @hoebbelsB 

Could you change this issue in a way we can solve something?

Checkboxes and clear descriptions is needed here.
