### ISSUE TITLE
Scrollspy is off by one in Firefox

### ISSUE THREAD

**Issue by andreElrico** [rx-angular/rx-angular#333]
# Description

1. on firefox 78 (not the most recent)

2. https://rx-angular.github.io/rx-angular/#/web/state/general/basic-setup?id=output-property-bindings

3. Scrollspy (read bar/ hightlight) is on point above (Input Property Bindings)

4. Im also off by one for the next menu points (`Updates based on previous state`, `Usage with services`) and others

![image](https://user-images.githubusercontent.com/44729345/94152225-9f950f00-fe7b-11ea-9866-5e73638ec0cd.png)

# Notes

Works perfectly on my chrome. Can someone confirm or reject?

**Comment by BioPhoton** [comment]
Thanks for the detailed issue!
This helps a lot.

@Karnaukhov-kh is the champion of or docs. 
Kirill, what d you say?

**Comment by Karnaukhov-kh** [comment]
Hi. We don't have an access to docsify source code but I will definitely check what we can do on our side. 

Thank you for reporting 👍

**Comment by BioPhoton** [comment]
Closed I favour of new docs
