### ISSUE TITLE
Research: general performance optimizations

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#352]
just an issue to gather information about other approaches/techniques to improve runtime performance of javascript/angular applications:

* https://codeburst.io/painting-and-rendering-optimization-techniques-in-browser-2e53a70e7ee
* https://codeburst.io/javascript-compiler-optimization-techniques-only-for-experts-58d6f5f958ca

**Comment by BioPhoton** [comment]
closed by #356
