### ISSUE TITLE
Two-way connect

### ISSUE THREAD

**Issue by muuvmuuv** [rx-angular/rx-angular#389]
# Problem Solved By The Feature

We are trying to build an onboarding process which includes three pages where some user input is saved into each step to cancel/continue or easily go back in the process. One of our components has itself a component level state service that holds the user input. Now I want to fill that component state with data saved before (when continuing the process) but also want to return changed input to the component and process state. ATM I am trying to use connect to connect the component state with the onboarding state. But because I need a button for resetting the progress, I would like the onboarding state to send the resetted state to the component state. This works pretty neat one-way but when I am now trying to fill the state it goes into an infinite loop, ofc because both sides are trying to update each other every time a change comes in.

# Solution

A two-way connect which is not turning into an infinite loop of change detection.

# Alternatives Considered

Any hints are highly appreciated.

I am currently just resetting both states separately through the button and use `.get()` initially but this is not scalable through the hole onboarding process.

# Additional Context

```ts

  filterCards: Card[] = [] // this is forwarded to the component and inserted into its state
//...
    this.filterCards = this.filterState.getFilter() // initially get onboarding state
//...
this.filterState.connect('filter', this.dradService.selectCards('filter')) // connect component filter to onboarding filter
```

```ts
  selectCards(zoneName: string): Observable<Card[]> {
    return this.select(
      pluck('zones', zoneName),
      select((zone) => selectVisibleCards(zone))
    )
  }
```

**Comment by BioPhoton** [comment]
Hi @muuvmuuv! Thanks a lot for this open issue.

From reading the I assume there is a problem with imperatively getting the state. Not 100% sure as I don't have a fully understanding of your problem.

Could you be so kind and set up a minimum example in stackblitz, please?

**Comment by BioPhoton** [comment]
Hi @muuvmuuv any updates here?
It really just need to be super minimal the demo. 

Also, maybe this does solve your problem?

**Comment by muuvmuuv** [comment]
Haven't had time yet, so I would just close this issue because the alternative way does work for us now but I have attached this issue to the workaround in our codebase to come back to it someday when its needed :)

For completeness, I will attach my screenshot here if anyone will ever come to the same or similar issue.

![r](https://user-images.githubusercontent.com/11534760/98915453-379d9500-24ca-11eb-9d82-fc2a07b53c6e.jpg)

**Comment by BioPhoton** [comment]
I added a link to my the previous answer as I forgot it. :)
