### ISSUE TITLE
Strategy management

### ISSUE THREAD

**Issue by Karnaukhov-kh** [rx-angular/rx-angular#399]
# TODO

- [ ] change active strategy at runtime for component, directive, or pipe. (service approach works only for directive and component)

# Problem
- It is impossible to set the default strategy in any way. `Local` is always default. 
- At the moment you can change strategy at runtime only for specific directive/pipe. #136 #184 #186
- There is no way to provide custom strategies.
- The current way of naming strategies is counterproductive to the number of different configurations. #294

# Solution

Provide a couple of injectionTokens to configure strategy related things at instantiation time and a service that will allow the switch of active strategy at runtime.

## Registering Strategies
To register a strategy you need to provide a name and `StrategyConfiguration` object. Strategies are registered in the `app.module` so they are shared.

```typescript
 @NgModule({
  providers: [
   {
      provide: RX_CUSTOM_STRATEGIES,
      useValue: [{
        name: 'myCustomStrategy1',
        cdScope: 'affectedPathAndChildren',
        checkMode: 'markAndRun',
        beforeCd$?: pipe(tap(value => console.log(value + 'render started'))),
        afterCd$?: pipe(tap(value => console.log(value + 'rendered'))),
        detach: true,
      }],
      multi: true
   }
  ] 
 })
 export class AppModule {}
```

### Default strategy
To register a default strategy you need to provide the strategy name as a string. 

#### Granularity
- **App module level**. 
- **Feature module level**.
- **Component level**.
- **Directive level**. 

#### Module
```typescript
 @NgModule({
  providers: [
   {
      provide: RX_DEFAULT_STRATEGY,
      useValue: 'myCustomStrategy1',
   }
  ] 
 })
 export class AppModule {}
```
#### Component
```typescript
 @Component({
  providers: [
   {
      provide: RX_DEFAULT_STRATEGY,
      useValue: 'myCustomStrategy1',
   }
  ] 
 })
 export class MyComponent {}
```
#### Directive
```typescript
 @Directive({
  providers: [
   {
      provide: RX_DEFAULT_STRATEGY,
      useValue: 'myCustomStrategy1',
   }
  ] 
 })
 export class MyDirective {}
```

## Change the current strategy at runtime

Strategy change can happen through service that can be `providedIn: 'root'` or on the component or directive level. 

For components and directives locally provided services will override the global one. Therefore fine-grained nested configuration is possible without interfering with the other directives/components.

As pipes don't have a `providers` field in decorator we have to instantiate on our own, otherwise, we will change strategy in the higher-level instance. This is a problem.

## Strategy holder service sketch

```typescript
@Inject({providedIn: 'root'})
class StrategyService {
  // Provides observable of default strategy from token.
  defaultStrategy$;
  // Exposes observable of custom and preregistered strategies.
  registeredStrategies$ ;

  constructor(
    @Inject(RX_DEFAULT_STRATEGY) private defaultStrategy: string,
    @Optional() @Inject(RX_CUSTOM_STRATEGIES) private customStrategies: string,
  ) {
  }
}
```

# Additional context

- Template module might be not a good idea because user gets functionality that they might not need (Unpatch for example).

## Tokens vs ForRoot
- If we choose forRoot - different modules will need to have their own implementation of `forRoot` that is not shareable. Furthermore, the approach of the central configuration module is unnecessary overhead. Because users will get more stuff that they might end up using.
- Tokens. If we would go for tokens we don't end up in the above issues but need to document tokens usage.

**Comment by BioPhoton** [comment]
Close as it needs a redesign
