### ISSUE TITLE
Binding multiple observables with one directive.

### ISSUE THREAD

**Issue by moshe5745** [rx-angular/rx-angular#402]
Current situation if we need bind 2 observables and use it in 1 place.

```
<ng-container *rxLet="observableNumber1$; let n1">
  <ng-container *rxLet="observableNumber2$; let n2">
    <app-number [number]="myFunction(n1, n2)"></app-number>
  </ng-container>
</ng-container>
```

Wanted behaviour: 

```
<ng-container *rxLet="observableNumber1$; let n1; observableNumber2$; let n2">
  <app-number [number]="myFunction(n1, n2)"></app-number>
</ng-container>
```

**Comment by BioPhoton** [comment]
From what I understand, you should use RxState to organize it in the class. Adoptions on the features are done after stable release and I'm not sure if this will ever make it.

Does the suggestion to use RxState help?

**Comment by moshe5745** [comment]
You mean to do something like this?:
```
public readonly combinedNumbersObject$: MyCombinedObjectType = combineLatest([
   this.observableNumber1$,
   this.observableNumber2$
])

<ng-container *rxLet="combinedNumbersObject$; let combinedNumbersObject;">
  <app-number [number]="myFunction(combinedNumbersObject)"></app-number>
</ng-container>
```
I must declare  MyCombinedObjectType for this. 
This is not so convenient.

**Comment by edbzn** [comment]
@moshe5745 From what I know if your objects are correctly typed the combination will be automagicaly inferred without redeclaring a type.

**Comment by BioPhoton** [comment]
I did an implementation where you can put an object of string:observable in a directive and it combined it inside 1,2 years ago. Guess exactly what you need. I stoppedusing it as I wouldhave to implementall other behaviors too to cover edgecases. E.g WithLatestFrom... 

What you could do is create a pipe that does the combineLatest for you.

Wdys?😁

**Comment by moshe5745** [comment]
Pipe is a nice idea, but how its going to solve the typing issue?
I will still need the types of the output object. Do i miss something?

**Comment by BioPhoton** [comment]
I guess so. It's just a rxjs function. They type infer very well

**Comment by moshe5745** [comment]
Ok...So you suggesting something like this?:
```
<ng-container *rxLet="observableNumber1$ | combinePipe: observableNumber1$ ; let n1;>
  <app-number [number]="myFunction(n1, n2)"></app-number>
</ng-container>
```

**Comment by moshe5745** [comment]
Ok, thanks. I will try the pipe with the infer-ration.

**Comment by moshe5745** [comment]
Ok...So you suggesting something like this?:
```
<ng-container *rxLet="observableNumber1$ | combinePipe: observableNumber2$ ; let n1;>
  <app-number [number]="myFunction(n1, n2)"></app-number>
</ng-container>
```

**Comment by BioPhoton** [comment]
No. Haha.. I meant to put that code in the class. CombineLatest there.

**Comment by BioPhoton** [comment]
Hi @moshe5745 we created [`accumulateObservable`](https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/src/lib/state/accumulateObservables.ts).
Have a look and also feel free to reopen if needed.
