### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#405]
# Problem Solved By The Feature

We have no schematics :(

# Solution

Schematics are implemented

**State:**
- [ ] `add` (no Modules to register, no postinstall work)
- [ ] `generate` component 
  - [ ] Ask for target component
  - [ ] Ask for inject or extend

**Template:**
- [ ] `add`
  - [ ] Add `LetModule`, `PushModule`, `UnpatchEventsModule` to `app.module.ts`
- [ ] `migration` minimal setup (rename `*rxLet="o$, suspense: view"` to `*rxLet="o$, rxSuspense: view"`)
- [ ] `generate` think about usecases???

**Comment by sis0k0** [comment]
.

**Comment by edbzn** [comment]
:wave: I would be happy to help on this too.

**Comment by BioPhoton** [comment]
Maybe we can move in the base and do different schematics in different PRs? @sis0k0

**Comment by edbzn** [comment]
I started bootstraping schematics files and I'm wondering how to organize it, I see two different alternatives : 

1- We put schematics directly in it's related library under a `schematics` directory. The library holds its schematics files including the build configuration. _This means we need to change the build process to transpile schematics along the library and put these files in the distribution folder._ 

2- We put schematics in dedicated publishable libraries seperated from core libraries (eg: `schematics-state`, `schematics-template`). We can use an a plugin here to let Nx handle the build process for us. _This way we can normally use the `affected:build` command._

What are your thoughts on this?

**Comment by BioPhoton** [comment]
I guess at lease nd-add should be in the libs folders. 

**Folder Structure:**
```
 libs/
├── state
│   ├── src
│   ├── schematics
│   │   └── commands
│   │       └── ng-add
│   │           ├── index.md
│   │           ├── index.ts
│   │           └── schema.json
│   ├── package.json
│   └── collection.json
├── template
│   ├── src
│   ├── schematics
│   │   └── commands
│   │       └── ng-add
│   │           ├── index.md
│   │           ├── index.ts
│   │           └── schema.json
│   ├── package.json
│   └── collection.json
└── schematics
    ├── src
    ├── schematics
    │   └── commands
    │       └── ng-add
    │           ├── index.md
    │           ├── index.ts
    │           └── schema.json
    ├── package.json
    └── collection.json
```

Not sure if we have that much schematics to ship different libs for state and template...
But in any case we should coordinate with @sis0k0 i believe

**Comment by sis0k0** [comment]
I prefer having two separate schematics libraries - one for `state` and one for `template`. Also, because of the different build commands, I'd prefer to have them separated from the actual `state` and `template` code:
```
 libs/
├── state
│   ├── src
│   ├── package.json
│   └── collection.json
└── state-schematics
    ├── src
    ├── schematics
    │   └── commands
    │       └── ng-add
    │           ├── index.md
    │           ├── index.ts
    │           └── schema.json
    ├── package.json
    └── collection.json
├── template
│   ├── src
│   ├── package.json
│   └── collection.json
└── template-schematics
    ├── src
    ├── schematics
    │   └── commands
    │       └── ng-add
    │           ├── index.md
    │           ├── index.ts
    │           └── schema.json
    ├── package.json
    └── collection.json
```

However, because we want to ship them together with the libraries, I'd put them in the `dist/` directories whenever `state` or `template` is ready to be published:

```
 dist/
├── state
│   ├── src
│   ├── schematics
│   │   └── commands
│   │       └── ng-add
│   │           ├── index.md
│   │           ├── index.ts
│   │           └── schema.json
│   ├── package.json
│   └── collection.json
├── template
│   ├── src
│   ├── schematics
│   │   └── commands
│   │       └── ng-add
│   │           ├── index.md
│   │           ├── index.ts
│   │           └── schema.json
│   ├── package.json
│   └── collection.json
```

**Comment by BioPhoton** [comment]
Regarding build setup:
I suggest we solve the different builds over targets.

```typescript
"projects": {
  "state": {
    "build-lib": {
      "options": {
        "deleteOutputPath": false
      }
    },
   "build-schematics": {
    },
    "build": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              { "command": "yarn rimraf ./dist/libs/state" },
              {"command": "nx run state:build-schematics"},
              {"command": "ts-node  ./tools/scripts/post-build-schematics.ts --projectName=schematics" },
              {"command": "nx run state:build-lib"}
            ]
    },
  }
}
```

1. Manual cleanup
2. Build schematics + copy .md, .json
3. Build lib without cleanup of dist

This way we don't need to create a separate lib in the repo

--- 

General:

- First goal should be ng-add for the libs
- Second having migrations running
- Third creating an nx-plugin for our performance measurement setup in combination with CI (Don't think too much about that for now)

**Comment by edbzn** [comment]
Good point I didn't thought about customizing build targets for transpiling schematics. @sis0k0 I started by the ng-add command for the state library, let me know if you want me to take another task.

**Comment by edbzn** [comment]
This issue can be updated. I will work on the state `generate` component schematic soon.

**Comment by BioPhoton** [comment]
🙏🍾
