### ISSUE TITLE
Feature Request: Ability to create an Effect Function that is not dependent on State

### ISSUE THREAD

**Issue by nartc** [rx-angular/rx-angular#423]
# Problem Solved By The Feature

I have the following usage of `rx-angular/state`.

- I call `router.navigate` as a side-effect.
![image](https://user-images.githubusercontent.com/25516557/99026812-7581d400-2531-11eb-8215-602dfdd14abd.png)
- In component, I just do something to `trigger` the effect
![image](https://user-images.githubusercontent.com/25516557/99026856-8a5e6780-2531-11eb-99a1-cd6cdb23876e.png)

In this particular case, my `trigger` is a `selected` property in my whole state. Although this works, I now have a `selected` prop that does not do anything else beside as a **trigger** which just adds unnecessary state.

# Solution

It would be really nice if `RxState` has a function that would create an `Effect Function` that can be called from the component, pass in the proper arguments then have these arguments act as the `trigger`. (https://ngrx.io/guide/component-store/effect)

I would like to be able to rewrite the code snippets in the screenshots above into the following:

```ts
// createEffect is a made-up method name on RxState
export class TodoStateService extends RxState<TodoState> {
   readonly goToSelectedTodo = this.createEffect((id$: Observable<number>) => {
      return id$.pipe(
         tap(id => this.router.navigate(['/todo', id]))
      )
   })
}
```

```ts
export class TodoComponent {
   constructor(private readonly todoStateService: TodoStateService) {}

   onEditClicked(id: number) {
      this.todoStateService.goToSelectedTodo(id);
   }
}
```

# alternatives Considered

- Alternative would be https://ngrx.io/guide/component-store/effect
- Or the current solution that I'm using as shown in the screenshots.
- Or create a `Subject` in `StateService`

```ts
export class TodoStateService {
   private $selected = new Subject<number>();

   constructor() {
      super();
      this.hold(this.$selected.pipe(...))
   }
   
   setSelected(selected: number) {
      this.$selected.next(selected);
   }
}
```

**Comment by BioPhoton** [comment]
related to #293

**Comment by BioPhoton** [comment]
Hi @nartc 

I had another look at this one.

So you have some trigger (click, fn call) that should fire a side effect. nothing else?

```typescript
trigger$ = new Subject();

rxEffect.hold(trigger$, (id) => this.navigateToId(id))
```

```html
<button (click)="trigger$.next(42)">navigate</button>
```

Does that work for you?

**Comment by nartc** [comment]
@BioPhoton Right. That would work. But that isn't any different than a `selected` state in my example, is it? I still have something (whether it is a `state` or a `subject`) to manage manually. I'd like RxState to manage that if possible.

**Comment by BioPhoton** [comment]
Can you help me to get the goal here, why don't just call it directly? 

```typescript
export class TodoComponent {
   onEditClicked(id: number) {
      this.router.navigate(['/todo', id])
   }
}
```

**Comment by nartc** [comment]
Ideally, the goal is to completely separate everything from the Component except for its RxState (let’s call it ComponentState from here down). The test will only need to ensure the interaction between the component and its ComponentState service. Rendering logic is ensured with testing the vm$ (or whatever the ComponentState exposes as public API for rendering) to emit correct values when some events/triggers occur.

Personally, I deem Navigation is a side-effect so I’d like to handle that in the ComponentState service if possible (as well as anything relating to Route/URL/QueryParams) 

By the way, this feature request is non-blocking in anyway. So no rush at all.

**Comment by BioPhoton** [comment]
If I understood you right here my answer. IMHO one Subject in a Service is OK compared to the logic of the effect you suggested.

**Your feature request**
```typescript
export class TodoStateService extends RxState<TodoState> {
   goToSelectedTodo = this.createEffect((id$: Observable<number>) => {
      return id$.pipe(
         tap(id => this.router.navigate(['/todo', id]))
      )
   })
   constructor(private router: Router) { 
   }
}
```



**How I would write based on your instructions**
```typescript
export class ComponentState extends RxEffects {
  trigger$ = new Subject<number>();
  goToSelectedTodo = this.trigger.next;
  constructor(private router: Router) {
    this.hold(trigger$, (id) => this.navigateToId(id))
  }
}  
```

Why I would still use the Subject is, it's easier to reason about, I cant really save lines of code with the other approach.
I can reuse the trigger if I like, and more important I can recombine the trigger also with other triggers.
This pays off in bigger components.

Please let me know what u think.

**Comment by nartc** [comment]
I can now see your point. That makes total sense and what you propose is hard to argue against. Thanks for the suggestion. Closing this.

**Comment by BioPhoton** [comment]
Linking this here as it is related: https://github.com/rx-angular/rx-angular/pull/1112
