### ISSUE TITLE
Throw error in hold stream stopped all other hold streams

### ISSUE THREAD

**Issue by allfayn** [rx-angular/rx-angular#435]
# Description

If one of the hold streams has an error when all other hold streams stoped

# Steps to Reproduce the Issue

Check  [stackblitz](https://stackblitz.com/edit/angular-ivy-mrmn6v?file=src%2Fapp%2Fapp.component.ts) example

```
this.hold(interval(1000), i => console.log(i));
this.hold(
  of(null).pipe(
    delay(5000),
      mergeMap(() => throwError("error"))
  )
);
```

Result in console:
`0
1
2
3
4
error`

# Related to Other Issues

#293 

# Solution

Add catchError in hold definition and return EMPTY when having some error

```
hold<S>(
    obsOrObsWithSideEffect: Observable<S>,
    sideEffectFn?: (arg: S) => void
  ): void {
    if (typeof sideEffectFn === 'function') {
      this.effectObservable.nextEffectObservable(
        obsOrObsWithSideEffect.pipe(catchError((e)=> {
          console.error(e)
          return EMPTY
        }),tap(sideEffectFn))
      );
      return;
    }
    this.effectObservable.nextEffectObservable(obsOrObsWithSideEffect.pipe(catchError((e)=> {
      console.error(e)
      return EMPTY
    })));
  }

```

**Comment by hoebbelsB** [comment]
hi @allfayn, thx for reporting!! :+1: 
 would u mind to create a PR or should we just fix it in your behalf? :)
