### ISSUE TITLE
globalThis fails in SSR/ngUniversal 

### ISSUE THREAD

**Issue by mhartington** [rx-angular/rx-angular#436]
# Description

Using `rx-angular/template` in a SSR env will throw an error about `window` due to global this.

# Steps to Reproduce the Issue

- Create a new angular app
- setup minimal rx-angular use case
- run `ng add @nguniversal/express-engine`
- run `npm run dev:ssr`

# Environment

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by BioPhoton** [comment]
Thx for the issue!!

**Comment by BioPhoton** [comment]
closed by #449
