### ISSUE TITLE
Extend Docs for Template

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#444]
# Problem Solved By The Feature

- [ ] 📚 Docs creation @Karnaukhov-kh
  - [ ] Mark them with a 🧪 icon
  - [ ] 📚📖Clarify Local Template Variable Scope https://github.com/angular/angular/pull/31195/files
  - [ ] 📚📖 Clarify usage of global strategy as a fallback option

# Solution

# alternatives Considered

# Additional Context

**Comment by Karnaukhov-kh** [comment]
Continued with web docs today and realised that first we need to update docs in the repo.

Is this issue still relevant or we can close it in favor or combine with #563?
