### ISSUE TITLE
Docs(template): import TemplateModule is not exported

### ISSUE THREAD

**Issue by ngfelixl** [rx-angular/rx-angular#500]
# Description

Hi everyone. While working with the **@rx-angular/template** module I noticed that in the [README](https://github.com/rx-angular/rx-angular/blob/master/libs/template/README.md) it says

```
import { TemplateModule } from '@rx-angular/template';
```

which is not exported from the package. However going with the specified alternative works fine, importing `LetModule` and `PushModule`. This block should be removed from the docs, I guess.

**Comment by BioPhoton** [comment]
Yes! :)

**Comment by tayambamwanza** [comment]
I got caught by this in an update just now, will refactor.
