### ISSUE TITLE
Document CDK dependency and new template release

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#554]
# Description

# Steps to Reproduce the Issue

# Environment

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by lincolnthree** [comment]
This looks good! Fix confirmed. However... there is another issue that seems to be undocumented. Not sure if it's caused by this or just by... other updates since the last version we've been able to use:

```
[ng] An unhandled exception occurred: The target entry-point "@rx-angular/template" has missing dependencies:
[ng]  - @rx-angular/cdk
Looks like we need to install @rx-angular/cdk manually as a dependency to get things working (additionally, version numbers don't match up on those libraries, which could confuse some folks)
```

Let me know if you'd like another issue opened.

**Comment by hoebbelsB** [comment]
i think the purpose of this issue was exactly documenting the missing dependency :)

**Comment by lincolnthree** [comment]
@hoebbelsB Woops, a bit of Copypasta there. My bad, lol. I thought I was typing that in another issue and didn't realize I'd put it here by accident :p
