### ISSUE TITLE
Question: Any problems with overriding the stock async pipe with push pipe?

### ISSUE THREAD

**Issue by Rush** [rx-angular/rx-angular#573]
I have a fairly big application and would like to add "push" pipe as an experimental optimization option that is easy to toggle for now. For a test I just wrote the following code:
```
import { ChangeDetectorRef, Pipe } from '@angular/core';
import { RxStrategyProvider } from '@rx-angular/cdk';
import { PushPipe } from '@rx-angular/template';

@Pipe({
    name: 'async',
    pure: false,
})
export class AsyncPushPipe<T> extends PushPipe<T> {
    constructor(strategyProvider: RxStrategyProvider, cdRef: ChangeDetectorRef) {
        super(strategyProvider, cdRef);
        console.log('AsyncPushPipe');
    }
}
```

The pipe seems to be working as a I get a ton of "AsyncPushPipe" log lines. Should I be aware of any surprises?

Thanks to this I will be able to conditionally enable/disable this at build time.

**Comment by hoebbelsB** [comment]
hi @Rush i'd rather recommend using the `LetDirective` instead. As a structural directive it is able to control a template which gets rendered completely on its own. This will benefit the performance of your application more than the push pipe will in its current state.

The only thing you might concern about are `NgZone` related optimizations. All of our components operate outside of `NgZone` and will patch into it if needed. There is an `@Input` parameter to control this behavior: `patchZone: boolean`.
The `PushPipe` is currently missing this, but will get shipped soon (#560) 
Expect more documentation on this topic in the upcoming weeks.

I hope I could help you out a bit.

**Comment by Rush** [comment]
@hoebbelsB yes, definitely I will look into the LetDirective however right now I am looking for some quick wins that don't make me commit into this solution yet. If the async pipe replacement is a success, I can follow up with an actual refactor of the code.

Wouldn't the `push` pipe help with performance at least due to coalescing? 

btw. I think having developers write `| push: 'strategy'; renderCallback; patchZone` by hand is a wrong approach. Developers need simple "no need to think" solutions. Unfortunately most developers aren't senior developers.

**Comment by hoebbelsB** [comment]
`async` should coalesce as well, the difference is that the push-pipe renders locally and does not rely on `markForCheck` bubbling up to `AppRef` and then performing an `AppRef#tick`. 

> btw. I think having developers write | push: 'strategy'; renderCallback; patchZone by hand is a wrong approach. Developers need simple "no need to think" solutions. Unfortunately most developers aren't senior developers.

you are right, thats why all of this is configured by default. These options are available if u want to customize stuff. So advanced users will have advanced possibilities :)

**Comment by BioPhoton** [comment]
Hi, @Rush thanks for the question! 

I tried to override async with push a while back.. It was working back then :)

Depending on why your app is slow I guess some let directives in the big templates and rxFor in the heavy lists should fix it and u don't have to replace that much.  But as mentioned, your approach should work.

**Comment by hoebbelsB** [comment]
lol ... I didn't get what you actually did until now :facepalm: 
@BioPhoton `rxFor` isn't even released yet. But you are right with your comments

**Comment by Rush** [comment]
I actually conducted a test in the production app. It wasn't a very scientific experiment but I did a few profiling sessions. The result was (more or less):
- Scripting time increased by 60%
- Rendering time cut by half

In the end I didn't see any noticeable improvement as it's hard to evaluate the trade balance with the scripting and rendering time. I will probably have to repeat my tests some other time. For now I'll keep using the stock async pipe.

**Comment by hoebbelsB** [comment]
this is actually what we want to achieve. in the end the components of `@rx-angular` will increase the amount of computational work in order to cut down rendering time. this is good because rendering is the most expensive task for the browser. Most of the time when you experience `frame drops` it is caused by too heavy rendering load tried to be executed at once. The goal should be to avoid `frame drops` to have a very smooth UX :)

**Comment by BioPhoton** [comment]
@Rush can I close this one?

**Comment by Rush** [comment]
Yes. Thank you. The answer is yes.
