### ISSUE TITLE
Universal Build Errors because of undefined reference to window

### ISSUE THREAD

**Issue by Kamshak** [rx-angular/rx-angular#579]
# Description

When doing a universal build with @rx-angular/template execution will fail because of the reference to window in https://github.com/rx-angular/rx-angular/blob/cfd47112c12bf7333e657c2f6b6e79d3d3eccda4/libs/cdk/src/lib/render-strategies/scheduler/scheduler.ts#L63. 

# Steps to Reproduce the Issue

Include `@rx-angular/template` in a server context.

# Environment

"@angular/platform-server": "11.0.8",
"@rx-angular/cdk": "^1.0.0-alpha.4",
"@rx-angular/template": "1.0.0-beta.24",
"@angular-devkit/build-angular": "0.1100.5",
"@nrwl/cli": "11.2.12",

Ivy Workspace: Yes

# Tasks to Resolve This

Use setTimeout instead of window.setTimeout maybe? No Idea to be honest 😄

**Comment by tayambamwanza** [comment]
Haha just bumped into this issue now, can't run universal.
