### ISSUE TITLE
Info: Chrome shows security warning for rx-angular.io

### ISSUE THREAD

**Issue by tmtron** [rx-angular/rx-angular#604]
# Problem Solved By The Feature

This is just an information, in case that you didn't know already.  
The current version of Google Chrome (Version 89.0.4389.90) shows a security warning when users visit [rx-angular.io](http://rx-angular.io) for the first time. 

You can try this in an **incognito window**:

![image](https://user-images.githubusercontent.com/20422904/111431317-ef9eb100-86fb-11eb-99a7-edadb47f7145.png)

# Solution

Not sure if you can do anything about this, except changing the domain name.  
Feel free to close this anytime.

# alternatives Considered

# Additional Context

**Comment by edbzn** [comment]
No warning on my side with the same chrome version.

**Comment by tonivj5** [comment]
> No warning on my side with the same chrome version.

Same here, no warning

**Comment by tmtron** [comment]
strange - did you try in incognito mode?

**Comment by tonivj5** [comment]
Nope, normal mode

**Comment by tmtron** [comment]
Yes, you should test in incognito mode to see what new users (i.e. who visit the page for the very first time) see. I guess that chrome will only show this warning once (and then remember the decision).

**Comment by tonivj5** [comment]
Works weel in incognito too. No warning

![image](https://user-images.githubusercontent.com/7110786/111441961-25e22d80-8708-11eb-81bd-6523be0e7ff2.png)

**Comment by tmtron** [comment]
oh well - maybe something strange on my side.  
I'll just close this.
