### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by arturovt** [rx-angular/rx-angular#612]
I'll be very short here :smile: 

That would be great to have some kind of CONTRIBUTING.md page where all developers will see the common rules (or standards) they should follow while making a PR.

That also would be great to have commit message conventions:

1. all possible scopes (cdk, template, ci, etc...)
2. all possible commit types (fix, feat, perf, ci, etc...)
3. how the commit description should look like, e.g. _full commit description + PR Close #ISSUE_NUMBER_HERE_

**Comment by hoebbelsB** [comment]
i agree :100:  ! tell me how, i will do it :smiley:

**Comment by hoebbelsB** [comment]
@arturovt lets start with a list here and we can extend it over time :)

# Scopes

* cdk
* cdk/zone-less ?
* template
* state
* docs
* demos
* schematics
* chore (ci/cd/workspace health)

# Commit types

* `fix` bugfixes
* `feat` a new feature
* `perf` performance improvements
* `docs` docs added/updated
* `refactor` code refactorings / lib restructuring
* `test` add / update tests
* `chore` build / ci related stuff

# Commit message description

TBH I would try to pick something from [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) and make it a bit less complicated to digest :)
