### ISSUE TITLE
Can't bind to 'rxLetSuspense' since it isn't a known property of 'ng-container'

### ISSUE THREAD

**Issue by muuvmuuv** [rx-angular/rx-angular#649]
# Description

I cannot get suspense working.

# Steps to Reproduce the Issue

https://codesandbox.io/s/empty-pond-hnrt9?file=/src/app/app.component.html

# Environment

```
Angular CLI: 11.2.x
Node: 15.x
OS: macos latest

Angular: 12.x
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
```

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by hoebbelsB** [comment]
hi @muuvmuuv this is our fault, because the documentation is not in sync with the code currently :(.

try the following:

```html
<ng-container
  *rxLet="
    observableNumber$;
    let n;
    rxError: error;
    rxComplete: complete;
    rxSuspense: suspense;
  "
>
  <app-number [number]="n"></app-number>
</ng-container>
```

**Comment by muuvmuuv** [comment]
No problem! That is what betas are for ;) do we want to keep that open with docs label or is this tracked elsewhere?

**Comment by hoebbelsB** [comment]
i think its tracked here #431

**Comment by BioPhoton** [comment]
Could we open an issue to fix the docs, or do it here?
