### ISSUE TITLE
Demo for error handling needs clarification

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#690]
# Description

The example for error handling here https://github.com/rx-angular/rx-angular/blob/671d3c259cc77f3b5f4df93ace1739d95c7d3bc8/apps/demos/src/app/features/template/rx-for/error-handling/error-handling-parent.component.ts
Is not intuitive. 
- How can I produce the error? 
- Why is the error happening?

@hoebbelsB could you have a quick look please?

**Comment by BioPhoton** [comment]
Any opinions @hoebbelsB?

**Comment by tmtron** [comment]
@BioPhoton  For some reason I cannot open your localhost link :)
I think this may be the [correct link](https://github.com/rx-angular/rx-angular/blob/671d3c259cc77f3b5f4df93ace1739d95c7d3bc8/apps/demos/src/app/features/template/rx-for/error-handling/error-handling-parent.component.ts)

**Comment by BioPhoton** [comment]
Updated! Thanks a lot @tmtron!

**Comment by hoebbelsB** [comment]
@BioPhoton I think you will find better insights in #831 and #832
