### ISSUE TITLE
Improve support for non-browser environments

### ISSUE THREAD

**Issue by edbzn** [rx-angular/rx-angular#726]
As a @rx-angular/template user I would like to have better support for non-browser environments, this is particularly relevant for testing and server environment where default strategy fails to render something.

- the documentation should mention these use cases and provides some guidelines,
- (optional, needs discussion) the library should provide some utils to improve DX (for instance [this](https://github.com/rx-angular/rx-angular/issues/714#issuecomment-832666021)),
- non-browser builds should not output irrelevant errors : 

```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
```

I would like to have your feedback before working on this.

**Comment by BioPhoton** [comment]
Sounds pretty good!

**Comment by BioPhoton** [comment]
Well,  the edge cases maybe?

**Comment by edbzn** [comment]
Related to #1314

**Comment by hoebbelsB** [comment]
@edbzn wasn't it closed by https://github.com/rx-angular/rx-angular/pull/820 ?

**Comment by edbzn** [comment]
There are points still not complete (doc and test utils) but it's tracked in another issue, let's close.
