### ISSUE TITLE
Can't bind to 'rxLetError' since it isn't a known property of 'ng-container'.

### ISSUE THREAD

**Issue by codingnuclei** [rx-angular/rx-angular#796]
**Steps to Reproduce**:

ng new my-app
npm install --save @rx-angular/template @rx-angular/cdk

Add `LetModule` to app.module `imports`

Use *rxLet with template-binding

See error.

**Example** 

I have created a [stackblitz](https://stackblitz.com/edit/angular-hnrtpr?file=src/app/app.component.ts) 

I have also done the same locally with a brand new project. Locally it does compile however, in the console I see the same sort of error: 

> core.js:10101 NG0303: Can't bind to 'rxLetSuspense' since it isn't a known property of 'ng-container'.

Am aware of this issue https://github.com/rx-angular/rx-angular/issues/201.  However it is suggesting it is fixed

**Comment by hoebbelsB** [comment]
sorry @codingnuclei,  you just got trapped by our poor API documentation :facepalm: 

https://stackblitz.com/edit/angular-6hru5j?file=src/app/app.component.html

Here is a link to a working solution. It's basically just `rxError` instead of `error` inside of the template.

```html
<ng-container *rxLet="
    observableNumber$;
    let n;
    rxError: error;
    rxSuspense: suspense;
    rxComplete: complete;
  ">
  {{n}}
</ng-container>
<ng-template #error>ERROR</ng-template>
<ng-template #complete>COMPLETE</ng-template>
<ng-template #suspense>SUSPENSE</ng-template>
```
