### ISSUE TITLE
Zone Configuration Tree Shaking

### ISSUE THREAD

**Issue by wSedlacek** [rx-angular/rx-angular#805]
# Description

It appears that the following import isn't properly being tree shaken.
```ts
import { zoneConfig } from '@rx-angular/cdk';
```

# Example
<img width="400" alt="Screen Shot 2021-06-03 at 12 08 32 AM" src="https://user-images.githubusercontent.com/8206108/120602746-2bded500-c400-11eb-8f60-0835e83547fa.png">

18.65Kb appears to be the full size of the CDK rather than just the zoneConfig which from my understanding should be quite small.

Without the import the pollyfill is much smaller.
<img width="504" alt="Screen Shot 2021-06-03 at 12 13 52 AM" src="https://user-images.githubusercontent.com/8206108/120603184-9859d400-c400-11eb-9f8c-920a4fb76df1.png">

# Reference

This appears to be the source of the majority of the bundle size (100 Kb from @angular/core)
https://github.com/rx-angular/rx-angular/blob/89151acb1ff6a42dee6c04dce1509bb31032a572/libs/cdk/zone-configurations/src/lib/zone-config.ts#L92-L98

**Comment by BioPhoton** [comment]
https://github.com/rx-angular/rx-angular/pull/728
Fixed it. We are working on migration scripts ATM.
