### ISSUE TITLE
[template] Could not resolve dependency for platform browser 11 with Angular 12

### ISSUE THREAD

**Issue by muuvmuuv** [rx-angular/rx-angular#807]
# Description

Our current Angular version is 12 and trying to install rx-angular/template causes a dependency error because it relies on v11 of platform-browser. This only occurs in npm v7 and above where peer and dependencies are strictly compared.

# Steps to Reproduce the Issue

Use Angular 12 and npm 7.

# Environment

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by BioPhoton** [comment]
THX for mentioning!

Should be fixed in next release

**Comment by BioPhoton** [comment]
Fixed in alpha.9
