### ISSUE TITLE
Naming suggestion for cdk/coercion package

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#815]
# Description

Angulars package for coercing is named "coercion". RxAngular's package is named "coercing".
If we aim for a connection to the already existing helpers the naming could be improved.

# Tasks to Resolve This

I suggest renaming the package to coercion as it is anyway not released.

Any thoughts @Karnaukhov-kh @hoebbelsB @edbzn @arturovt

**Comment by BioPhoton** [comment]
same for coalescing btw haha

**Comment by hoebbelsB** [comment]
I see those options:

* `@rx-angular/coalesce` & `@rx-angular/coerce` 
* `@rx-angular/coalescing` & `@rx-angular/coercing`
* `@rx-angular/coalescence` & `@rx-angular/coercion` => related to @angular/cdk

**Comment by hoebbelsB** [comment]
as much as i like the nerdy sound of `coalescence` I would tend towards `coalescing` and `coercing`. But thats 100% subjective

**Comment by BioPhoton** [comment]
I was also giggling when I was reading it. 😂

how are all other existing packages aligned to it?

**Comment by hoebbelsB** [comment]
lets list them:
* coalescing
* coercing
* notifications
* render-strategies
* state
* template-management
* zone-configuration
* zone-less

I think it's impossible to find a pattern where every package fits in well. 
render-strategies could get rendering though

**Comment by BioPhoton** [comment]
- notifications 
- render-strategies
- state

seem odd to me too.

**Comment by hoebbelsB** [comment]
* notification
* rendering

state is fine imo.

I would also suggest to rename template-management to template?

`@rx-angular/template` makes use of `@rx-angular/cdk/template` sounds reasonable. Same goes for state i'd say?

**Comment by BioPhoton** [comment]
The template uses notification and rendering. Hmmm...
Naming is hard...

Let's include this in the core team meeting?
