### ISSUE TITLE
Documentation template for web docs

### ISSUE THREAD

**Issue by Karnaukhov-kh** [rx-angular/rx-angular#822]
# Resources

**Example applications:**  
A demo application is available on [GitHub](https://github.com/BioPhoton/rx-angular-cdk-coercing).

# ✨Motivation

Explain the problem

# 📦 Resources

List of resources related to the issue feature solve

# 😓 Approaches

Other approaches to solving the problem.

# 🎯 RxAngular solution

## Setup

How to setup a solution

## Usage

Example of feature usage

## Best practices

----

## Guides

Detailed description with more complex code example

# ☠️ Risks

What can break

**Comment by LayZeeDK** [comment]
Hi @Karnaukhov-kh,

Is this issue still relevant?

**Comment by Karnaukhov-kh** [comment]
Hi. It was our attempt to standardize docs. Long time outdated 😅
