### ISSUE TITLE
Persistent state option

### ISSUE THREAD

**Issue by muuvmuuv** [rx-angular/rx-angular#885]
# Problem Solved By The Feature

Easier debugging when depending on other state properties. And maybe some more?

# Solution

An option to save state between page reloads/route changes.

# alternatives Considered

Self implement:

```ts
// RxState component and Ionic Storage plugin example
  constructor() {
    super()

    Storage.get({ key: "state" }).then((cached) =>
      this.set((oldState) => ({
        ...oldState,
        ...JSON.parse(String(cached.value)),
      }))
    )

    this.state$
      .pipe(
        takeUntil(this.destroyed), // any internal events for this?
        exhaustMap((state) =>
          Storage.set({
            key: "state",
            value: JSON.stringify(state),
          })
        )
      )
      .subscribe()
  }
```

# Additional Context

Additional feature to provide own "caching" method like Ionic Storage.

**Comment by BioPhoton** [comment]
Nice idea! :)

I guess it could be extracted in a function and kept as a side effect. 
Maybe something like this?

```typescript
function setupStorage(state: RxState) {

// hydrate from store on init
    Storage.get({ key: "state" }).then((cached) =>
      state.set((oldState) => ({
        ...oldState,
        ...JSON.parse(String(cached.value)),
      }));

// update store on state change

state.hold(
  state.$.pipe(
      // saves latest value. exhaustMap would drop updates inbetween
      switchMap((state) =>
          Storage.set({
            key: "state",
            value: JSON.stringify(state),
          })
      )
  )
);

}


// RxState component and Ionic Storage plugin example
  constructor() {
    super()

   setupStorage(this)
  }

```

Also, an option is to create your custom service and extend from RxState.

Let me know if it helped. :)
If those 2 options help you to organize the code better please close it.

**Comment by muuvmuuv** [comment]
Hey @BioPhoton, thanks for the optimizations! I think it would be a good fit in the docs. I rethought my initial idea of having an option or something in RxState but since there are so much different caching methods out there it's better to provide some guidance for others to set up "caching" properly.

**Comment by muuvmuuv** [comment]
Would it make sense to schedule those store updates with `animationFrameScheduler` to keep heavy state change updates away from the user UX?

**Comment by muuvmuuv** [comment]
Oh, I just realized that this does not work if you need the hydrated state in a route guard since it's async... need to figure that out now.

**Comment by muuvmuuv** [comment]
Okay, never mind, just calling the setup function from the module constructor works just fine.

Here is my solution:

```ts
/* eslint-disable @typescript-eslint/ban-types */

import { Storage } from '@capacitor/storage'
import { RxState } from '@rx-angular/state'
import { animationFrameScheduler, auditTime, switchMap } from 'rxjs'

/**
 * Help to hydrate a RxState from store.
 */
export function rxStateSetupStorage<T extends object>(name: string, state: RxState<T>) {
  // Hydrate from store

  Storage.get({ key: name }).then((cached) => {
    console.info(`[RxState] Hydrating ${name}...`)

    state.set((oldState) => ({
      ...oldState,
      ...JSON.parse(String(cached.value)),
    }))
  })

  // Update store on state change

  state.hold(
    state.$.pipe(
      auditTime(0, animationFrameScheduler),
      switchMap((state) => {
        console.info(`[RxState] Updating ${name}...`)

        return Storage.set({
          key: name,
          value: JSON.stringify(state),
        })
      })
    )
  )
}
```

And in `some.module.ts`:

```ts
// ...
  providers: [CreateStateService],
})
export class CreateModule {
  constructor(state: CreateStateService) {
    rxStateSetupStorage(STORAGE_KEY_CREATE_STATE, state)
  }
}
```

**Comment by BioPhoton** [comment]
> Would it make sense to schedule those store updates with animationFrameScheduler to keep heavy state change updates away from the user's UX?

requestIdleCallback is the thing we need here as it is not related to something visible. The user will not feel the delay and other more important tasks can go first.

Another nerdy detail is, request AnimationFrame triggers style recalc and we don't need it.

**Comment by BioPhoton** [comment]
@muuvmuuv if you don't mind I would close this issue as the solution can easily be implemented outside of the lib.
Feel free to reopen if needed.
