### ISSUE TITLE
If parent component doesn't have a context (e.g. null) it'll error

### ISSUE THREAD

**Issue by wesselvdv** [rx-angular/rx-angular#908]
I believe a simple check to ensure that the value isn't null or undefined should suffice.

https://github.com/rx-angular/rx-angular/blob/75aa3571a5764c397ea3002bf1c149211d11497e/libs/cdk/src/lib/template-management/utils.ts#L93

I am getting this error when I have an rxLet inside a component with a parent that has the mat-button directive:

`ASSERTION ERROR: Target expected [Expected=> null != null <=Actual]`

**Comment by edbzn** [comment]
I also have seen this error, we should consider activating the strict mode to avoid this kind of issue.

**Comment by edbzn** [comment]
Closing as it is fixed in @rx-angular/template@1.0.0-beta-33, feel free to reopen if still occurring.
