### ISSUE TITLE
Error during app startup - regression between 1.4.4 <-> 1.4.5

### ISSUE THREAD

**Issue by kroeder** [rx-angular/rx-angular#928]
# Description

With version 1.4.5 you cannot run an app anymore due to this error

```
Error: ./node_modules/@rx-angular/state/fesm2015/state.js 586:146-164
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/@rx-angular/state/fesm2015/state.js 588:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/@rx-angular/state/fesm2015/state.js 586:34-55
"export 'ɵɵngDeclareFactory' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/@rx-angular/state/fesm2015/state.js 587:35-59
"export 'ɵɵngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'
```

However, if you pin down the version to 1.4.4 everything works as expected

# Steps to Reproduce the Issue

- Checkout https://github.com/kroeder/rx-angular-state-regression-reproduction
- `ng serve`

# Environment

```
Angular CLI: 11.2.14
Node: 12.21.0
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.1.5
```

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by hoebbelsB** [comment]
thx @kroeder !! We recently added partial Ivy compilation to the state package. That is most probably what causes the problems on your end. Did u have the chance to upgrade to v12 in the meantime?

**Comment by kroeder** [comment]
Unfortunately that's not possible. We use ex angular in dozens of apps and while we try to keep them up to date some only patch things for maintenance

What I'm wondering is that angular 11 apps do have ivy support. Why does this package with activated ivy support now break things? In our library I also have activated ivy support and it does work as expected (if I did nothing wrong)

**Comment by BioPhoton** [comment]
@edbzn could this be due to a change in NX setup?

**Comment by edbzn** [comment]
@BioPhoton No we just enabled Ivy and we broke the compatibility, we should roll back because it's a breaking change.
