### ISSUE TITLE
Error in the subject prevent to emit again in hold

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#967]
# Description

After I click the login button I got error from the server. which is good because login was failed.
next time I click the login button again, it's not invoke the subject and not trigger the login service.

https://codesandbox.io/s/intelligent-mendeleev-52shh?file=/src/app/app.component.ts

@rx-angular/state v.1.4.6

# Steps to Reproduce the Issue
```
 template: `
    <button (click)="login()">login</button>
    {{ state$ | async | json }}
  `,
...
export class AppComponent extends RxState<{ user: any }> {
  readonly login$ = new Subject<{ email: string; password: string }>();

  state$ = this.select();

  readonly loginEffect$ = this.hold(
    this.login$.pipe(
      tap(() => {
        console.log("in login!!");
      }),
      switchMap(({ email, password }) =>
        this.authApiService.login({ email, password })
      ),
      tap({
        next: ({ user }) => {
          console.log("in tip!!");
          this.set({ user });
          //    this.router.navigate(["/"]);
        },
        error: (response) => {
          console.log({ response });
          this.set({ error: response?.error?.error || "ERROR" });
        }
      }),
      startWith({ error: null, pending: true }),
      endWith({ pending: false })
    )
  );

  constructor(private authApiService: AuthApiService) {
    super();
  }

  login() {
    this.login$.next({ email: "gmail@gmail.com", password: "blabla" });
  }
}
```

# Environment

# Related to Other Issues

# Tasks to Resolve This

# Notes

**Comment by hoebbelsB** [comment]
you are missing a `catchError` sadly the error is swallowed and the stream dies after it. Anyway, take a look #966 :)

Btw. `state.hold(trigger$, () => state.set())` is unrecommended. You should use connect here.

**Comment by jon9090** [comment]
@hoebbelsB thank you for your quick response!
