### ISSUE TITLE
test(cdk-coercing): implement tests for coerceDistinctWith

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#970]
# Description

implement tests for the `coerceDistinctWith` OperatorFunction.
The operator takes an `Observable<ObservableInput<T>>` and an optional flatteningOperator (aka `switchAll`, `mergeAll`, ...) and forwards only distinct values after applying the flatteningOperator.
Feel free to update the jsDocs as well so docs get automatically generated for the operator.

e.g.
```ts
const inputs$ = new Subject<string, Observable<string>>;
inputs$.pipe(
 coerceDistinctWith()
).subscribe(console.log);

inputs$.next('cat');
inputs$.next(of('cat'));
inputs$.next(of('dog'));

// output: ['cat', 'dog']

```

Good example for other marble test implementations are:
* [coalesceWith](https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/coalescing/spec/coalesceWith.spec.ts)
* [onStrategy](https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/spec/render-strategies/onStrategy.spec.ts)

**Comment by exequiel09** [comment]
@hoebbelsB I'll take this on. Please assign it to me 😅 If possible 😅
