### ISSUE TITLE
test(cdk-coercing): implement tests for coerceAllFactory

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#972]
# Description

implement tests for the `coerceAllFactory` factory function. (libs/cdk/coercing/src/lib/coerce-all-factory.ts).
This function is returning an object to handle the process of merging a stream of Observables (`Observable<Observable<T>>`) into one Observable output stream revealing the inner values.

It is especially useful for Observable `@Input()` properties and is used in `rxLet`, `rxIf`, `rxFor`, ...

Feel free to create tests with different input parameters for `subjectFactory` (`Subject`, `ReplaySubject`, `BehaviorSubject`) and  `flattenOperator` (`switchAll`, `mergeAll`, `concatAll`).

Feel free to some jsDocs as well so docs get automatically generated for the operator.

e.g.
```ts
// default behavior:

const inputHandler = coerceAllFactory<string>(
    () => new ReplaySubject<string>(1)
  );
const val$ = of('hello dear contributor');
inputHandler.next(val$);

inputHandler.subscribe(console.log);

// output: 'hello dear contributor';

// custom flattening

const inputHandlerConcat = coerceAllFactory<string>(
    () => new ReplaySubject<string>(1),
    concatAll()
  );
const val$ = from(['hello', 'dear', 'contributor']);
inputHandlerConcat.next(val$);

inputHandlerConcat.subscribe(console.log);

// output: 'hellodearcontributor'

```

Good example for other marble test implementations are:
* [coalesceWith](https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/coalescing/spec/coalesceWith.spec.ts)
* [onStrategy](https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/spec/render-strategies/onStrategy.spec.ts)

**Comment by NileshPatel17** [comment]
@hoebbelsB I am new to writing rxjs test case. let me know if this makes sense.. Below both test cases are passing.

```
it('Test 1', () => {
        const value = 'hello dear contributor'
        const inputHandler = coerceAllFactory<string>(
            () => new ReplaySubject<string>(1)
        );
        const val$ = of(value);
        inputHandler.next(val$);
        inputHandler.values$.subscribe(data => {
            expect(data).toBe(value)
        });

    })

    it('Test 2', () => {
        testScheduler.run(({ expectObservable }) => {
            const value = "hello dear contributor";
            const exp = 'a';
            const inputHandler = coerceAllFactory<string>(
                () => new ReplaySubject<string>(1)
            );
            const val$ = of(value);
            inputHandler.next(val$);
            const result = inputHandler.values$
            expectObservable(result).toBe(exp, { a: value });
        });
    });
```
