### ISSUE TITLE
Docs: a better explanation of strategy

### ISSUE THREAD

**Issue by moniuch** [rx-angular/rx-angular#973]
Would you please consider improving the explanation of the `strategy` parameter (https://github.com/rx-angular/rx-angular/blob/master/libs/template/docs/api/let-directive.md)
It is not exactly clear what sort of string is supposed to be supplied for the subject. Is `'local'` a predefined constant? What other values can land in there?

[BTW I would suggest adding a separate ticket category for docs improvement, in the GitHub template.]

**Comment by hoebbelsB** [comment]
I think strategies are already pretty well described here: https://github.com/rx-angular/rx-angular/blob/master/libs/cdk/docs/render-strategies/strategies.md we would just need to link it properly to the directives docs?

**Comment by hoebbelsB** [comment]
now strategy docs are in really good shape, closing this one! https://github.com/rx-angular/rx-angular/tree/main/libs/cdk/render-strategies/docs
